[package]
name = "twine-cli"
description = "Twine font and image converters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "twine"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
