// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/frame3.png --format argb8888 --name FRAME3 --out crates/twine-demos/src/assets/frame3.rs --crate-path twine::image
// Input SHA-256: 3c5cfe5b96e874691eb2b686cbf1c76a2a3c575278c035f44d09c39e26262bfe
// twine-image: format=ARGB8888 w=32 h=32 stride=128 flags=0x00 compression=none stored=4096 size=4096

/// `FRAME3` (32×32 `ARGB8888`).
pub static FRAME3: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 32,
        h: 32,
        stride: 128,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("frame3.bin"),
);
