// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/frame2.png --format argb8888 --name FRAME2 --out crates/twine-demos/src/assets/frame2.rs --crate-path twine::image
// Input SHA-256: 947d2c5bb6e9f1428e0737af840e1963c2fac9aec066195032645d9e38cd7e8b
// twine-image: format=ARGB8888 w=32 h=32 stride=128 flags=0x00 compression=none stored=4096 size=4096

/// `FRAME2` (32×32 `ARGB8888`).
pub static FRAME2: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 32,
        h: 32,
        stride: 128,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("frame2.bin"),
);
