// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/frame0.png --format argb8888 --name FRAME0 --out crates/twine-demos/src/assets/frame0.rs --crate-path twine::image
// Input SHA-256: 04000d41383dbd2ef15b69b97d7b48e7c7e3ea76ba4ac844ff784c13700d9bd8
// twine-image: format=ARGB8888 w=32 h=32 stride=128 flags=0x00 compression=none stored=4096 size=4096

/// `FRAME0` (32×32 `ARGB8888`).
pub static FRAME0: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 32,
        h: 32,
        stride: 128,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("frame0.bin"),
);
