// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/frame1.png --format argb8888 --name FRAME1 --out crates/twine-demos/src/assets/frame1.rs --crate-path twine::image
// Input SHA-256: 84dc8e442793cd95f0025bd823af23a60b77ec0be630d786f7923203dcd1208f
// twine-image: format=ARGB8888 w=32 h=32 stride=128 flags=0x00 compression=none stored=4096 size=4096

/// `FRAME1` (32×32 `ARGB8888`).
pub static FRAME1: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 32,
        h: 32,
        stride: 128,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("frame1.bin"),
);
