// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/power_off.png --format argb8888 --name POWER_OFF --out crates/twine-demos/src/assets/power_off.rs --crate-path twine::image
// Input SHA-256: 740b9eb18289f4979d0541f63ffdd0c4c006811fd4e246a07c5fa1f31ff80ca3
// twine-image: format=ARGB8888 w=36 h=36 stride=144 flags=0x00 compression=none stored=5184 size=5184

/// `POWER_OFF` (36×36 `ARGB8888`).
pub static POWER_OFF: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 36,
        h: 36,
        stride: 144,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("power_off.bin"),
);
