// Generated by `twine image`; do not edit.
// Command: twine image --in crates/twine-demos/assets/power_on.png --format argb8888 --name POWER_ON --out crates/twine-demos/src/assets/power_on.rs --crate-path twine::image
// Input SHA-256: 3d8a3fe7020c0785744e5484a4101f6e280da668b9d20ca196d592c95d6e7e95
// twine-image: format=ARGB8888 w=36 h=36 stride=144 flags=0x00 compression=none stored=5184 size=5184

/// `POWER_ON` (36×36 `ARGB8888`).
pub static POWER_ON: twine::image::Image = twine::image::Image::new_static(
    twine::image::ImageHeader {
        format: twine::image::ColorFormat::Argb8888,
        w: 36,
        h: 36,
        stride: 144,
        flags: twine::image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("power_on.bin"),
);
