[package]
name = "twine-demos"
description = "Demo applications shared by simulator and firmware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
twine = { path = "../twine", default-features = false, features = ["montserrat-20"] }

[dev-dependencies]
twine = { path = "../twine", features = ["std"] }
twine-testing = { path = "../twine-testing" }
critical-section = { version = "1", features = ["std"] }
