// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format i8 --dither --name LOGO_I8 --out examples/src/assets/logo_i8.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=I8 w=64 h=64 stride=64 flags=0x00 compression=none stored=5120 size=5120

/// `LOGO_I8` (64×64 I8).
pub static LOGO_I8: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::I8,
        w: 64,
        h: 64,
        stride: 64,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_i8.bin"),
);
