// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format rgb565a8 --compress rle --name LOGO_RLE --out examples/src/assets/logo_rle.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=RGB565A8 w=64 h=64 stride=128 flags=0x02 compression=rle stored=4892 size=12288

/// `LOGO_RLE` (64×64 `RGB565A8`).
pub static LOGO_RLE: twine_image::Image = twine_image::Image {
    header: twine_image::ImageHeader {
        format: twine_image::ColorFormat::Rgb565A8,
        w: 64,
        h: 64,
        stride: 128,
        flags: twine_image::ImageFlags::from_bits_retain(0x02),
    },
    data: twine_image::ImageData::Compressed {
        method: twine_image::Compression::Rle,
        data: include_bytes!("logo_rle.bin"),
        decompressed_size: 12288,
    },
};
