// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format i2 --dither --name LOGO_I2 --out examples/src/assets/logo_i2.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=I2 w=64 h=64 stride=16 flags=0x00 compression=none stored=1040 size=1040

/// `LOGO_I2` (64×64 I2).
pub static LOGO_I2: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::I2,
        w: 64,
        h: 64,
        stride: 16,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_i2.bin"),
);
