// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format l8 --name LOGO_L8 --out examples/src/assets/logo_l8.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=L8 w=64 h=64 stride=64 flags=0x00 compression=none stored=4096 size=4096

/// `LOGO_L8` (64×64 `L8`).
pub static LOGO_L8: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::L8,
        w: 64,
        h: 64,
        stride: 64,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_l8.bin"),
);
