// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format argb8888-premultiplied --name LOGO_ARGB8888_PREMULTIPLIED --out examples/src/assets/logo_argb8888_premultiplied.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=ARGB8888_PREMULTIPLIED w=64 h=64 stride=256 flags=0x00 compression=none stored=16384 size=16384

/// `LOGO_ARGB8888_PREMULTIPLIED` (64×64 ARGB8888_PREMULTIPLIED).
pub static LOGO_ARGB8888_PREMULTIPLIED: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::Argb8888Premultiplied,
        w: 64,
        h: 64,
        stride: 256,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_argb8888_premultiplied.bin"),
);
