// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format a4 --name LOGO_A4 --out examples/src/assets/logo_a4.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=A4 w=64 h=64 stride=32 flags=0x00 compression=none stored=2048 size=2048

/// `LOGO_A4` (64×64 `A4`).
pub static LOGO_A4: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::A4,
        w: 64,
        h: 64,
        stride: 32,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_a4.bin"),
);
