// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format argb8888 --compress lz4 --name LOGO_LZ4 --out examples/src/assets/logo_lz4.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=ARGB8888 w=64 h=64 stride=256 flags=0x02 compression=lz4 stored=3538 size=16384

/// `LOGO_LZ4` (64×64 ARGB8888).
pub static LOGO_LZ4: twine_image::Image = twine_image::Image {
    header: twine_image::ImageHeader {
        format: twine_image::ColorFormat::Argb8888,
        w: 64,
        h: 64,
        stride: 256,
        flags: twine_image::ImageFlags::from_bits_retain(0x02),
    },
    data: twine_image::ImageData::Compressed {
        method: twine_image::Compression::Lz4,
        data: include_bytes!("logo_lz4.bin"),
        decompressed_size: 16384,
    },
};
