// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format i1 --dither --name LOGO_I1 --out examples/src/assets/logo_i1.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=I1 w=64 h=64 stride=8 flags=0x00 compression=none stored=520 size=520

/// `LOGO_I1` (64×64 `I1`).
pub static LOGO_I1: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::I1,
        w: 64,
        h: 64,
        stride: 8,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_i1.bin"),
);
