// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/twine_logo.png --format rgb565-swapped --name LOGO_RGB565_SWAPPED --out examples/src/assets/logo_rgb565_swapped.rs
// Input SHA-256: a0a83e3bc12c7cf9163aa791b6a93ba93ae05637468615d09f4a2153bd8c04d5
// twine-image: format=RGB565_SWAPPED w=64 h=64 stride=128 flags=0x00 compression=none stored=8192 size=8192

/// `LOGO_RGB565_SWAPPED` (64×64 `RGB565_SWAPPED`).
pub static LOGO_RGB565_SWAPPED: twine_image::Image = twine_image::Image::new_static(
    twine_image::ImageHeader {
        format: twine_image::ColorFormat::Rgb565Swapped,
        w: 64,
        h: 64,
        stride: 128,
        flags: twine_image::ImageFlags::from_bits_retain(0x00),
    },
    include_bytes!("logo_rgb565_swapped.bin"),
);
