// Generated by `twine image`; do not edit.
// Command: twine image --in assets/images/photo.png --format rgb565 --compress lz4 --name PHOTO_LZ4 --out examples/src/assets/photo_lz4.rs
// Input SHA-256: c0ba03487a06719fc27cd1e33c1707a14e6e925f6afcf91e4f7e2f1ced3722b3
// twine-image: format=RGB565 w=96 h=64 stride=192 flags=0x02 compression=lz4 stored=1901 size=12288

/// `PHOTO_LZ4` (96×64 `RGB565`).
pub static PHOTO_LZ4: twine_image::Image = twine_image::Image {
    header: twine_image::ImageHeader {
        format: twine_image::ColorFormat::Rgb565,
        w: 96,
        h: 64,
        stride: 192,
        flags: twine_image::ImageFlags::from_bits_retain(0x02),
    },
    data: twine_image::ImageData::Compressed {
        method: twine_image::Compression::Lz4,
        data: include_bytes!("photo_lz4.bin"),
        decompressed_size: 12288,
    },
};
