//! `cargo xtask progress`: regenerates `docs/plan/PROGRESS.md` from the phase files.
//!
//! Ticks, dates and notes of existing entries are preserved (matched by step id); steps that no
//! longer exist in any phase file are listed under `## Removed steps`. Idempotent.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;

use crate::util::{R, workspace_root};

const SEP: &str = " — ";
const HEADER: &str =
    "# Progress\n<!-- generated by `cargo xtask progress`; ticks and notes are preserved -->\n";
const REMOVED: &str = "## Removed steps";

/// One phase file: its title (first `# ` line) and its steps.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Phase {
    /// Title without the leading `# `.
    pub title: String,
    /// `(id, title)` pairs in file order.
    pub steps: Vec<(String, String)>,
}

/// An entry parsed from an existing PROGRESS.md.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Entry {
    ticked: bool,
    title: String,
    /// `" — <date> — <note>"` tail, verbatim (empty when none).
    tail: String,
}

/// Whether `s` is a step id `P\d\d.S\d\d`.
fn is_step_id(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() == 7
        && b[0] == b'P'
        && b[1].is_ascii_digit()
        && b[2].is_ascii_digit()
        && b[3] == b'.'
        && b[4] == b'S'
        && b[5].is_ascii_digit()
        && b[6].is_ascii_digit()
}

fn is_date(s: &str) -> bool {
    let b = s.as_bytes();
    b.len() == 10
        && b.iter().enumerate().all(|(i, c)| {
            if i == 4 || i == 7 {
                *c == b'-'
            } else {
                c.is_ascii_digit()
            }
        })
}

/// Parses a phase file's content.
pub fn parse_phase(content: &str) -> Phase {
    let mut title = String::new();
    let mut steps = Vec::new();
    for line in content.lines() {
        if title.is_empty()
            && let Some(t) = line.strip_prefix("# ")
        {
            title = t.trim().to_string();
        }
        if let Some(rest) = line.strip_prefix("### ")
            && let Some((id, t)) = rest.split_once(SEP)
            && is_step_id(id)
            && !t.trim().is_empty()
        {
            steps.push((id.to_string(), t.trim_end().to_string()));
        }
    }
    Phase { title, steps }
}

/// Parses the step lines of an existing PROGRESS.md (ticked or not), keyed by id.
fn parse_progress(content: &str) -> BTreeMap<String, Entry> {
    let mut map = BTreeMap::new();
    for line in content.lines() {
        let (ticked, rest) = if let Some(r) = line.strip_prefix("- [x] ") {
            (true, r)
        } else if let Some(r) = line.strip_prefix("- [X] ") {
            (true, r)
        } else if let Some(r) = line.strip_prefix("- [ ] ") {
            (false, r)
        } else {
            continue;
        };
        let (id, rest) = rest.split_once(SEP).unwrap_or((rest.trim_end(), ""));
        if !is_step_id(id) {
            continue;
        }
        let segs: Vec<&str> = rest.split(SEP).collect();
        let (title, tail) = match segs.iter().skip(1).position(|s| is_date(s.trim())) {
            Some(i) => (segs[..=i].join(SEP), format!("{SEP}{}", segs[i + 1..].join(SEP))),
            None => (rest.to_string(), String::new()),
        };
        map.insert(id.to_string(), Entry { ticked, title, tail });
    }
    map
}

fn step_line(out: &mut String, id: &str, title: &str, entry: Option<&Entry>) {
    let (mark, tail) = match entry {
        Some(e) if e.ticked => ("x", e.tail.as_str()),
        Some(e) => (" ", e.tail.as_str()),
        None => (" ", ""),
    };
    let _ = writeln!(out, "- [{mark}] {id}{SEP}{title}{tail}");
}

/// Renders the new PROGRESS.md for `phases`, preserving ticks/notes from `existing`.
pub fn render(phases: &[Phase], existing: &str) -> String {
    let old = parse_progress(existing);
    let mut out = String::from(HEADER);
    let mut seen = HashSet::new();
    for p in phases {
        let _ = writeln!(out, "\n## {}\n", p.title);
        for (id, title) in &p.steps {
            seen.insert(id.as_str());
            step_line(&mut out, id, title, old.get(id));
        }
    }
    let removed: Vec<_> = old.iter().filter(|(id, _)| !seen.contains(id.as_str())).collect();
    if !removed.is_empty() {
        let _ = writeln!(out, "\n{REMOVED}\n");
        for (id, e) in removed {
            step_line(&mut out, id, &e.title, Some(e));
        }
    }
    out
}

/// Runs the command: reads `docs/plan/phase-*.md`, rewrites `docs/plan/PROGRESS.md`.
pub fn run() -> R {
    let dir = workspace_root().join("docs/plan");
    if !dir.is_dir() {
        println!("progress: no planning files in this checkout; nothing to do");
        return Ok(());
    }
    let mut files: Vec<_> = std::fs::read_dir(&dir)?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            p.file_name().and_then(|n| n.to_str()).is_some_and(|n| {
                n.starts_with("phase-")
                    && std::path::Path::new(n)
                        .extension()
                        .is_some_and(|e| e.eq_ignore_ascii_case("md"))
            })
        })
        .collect();
    files.sort();
    let mut phases = Vec::new();
    for f in &files {
        phases.push(parse_phase(&std::fs::read_to_string(f)?));
    }
    let path = dir.join("PROGRESS.md");
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let new = render(&phases, &existing);
    let steps: usize = phases.iter().map(|p| p.steps.len()).sum();
    let done = new.lines().filter(|l| l.starts_with("- [x]")).count();
    if new == existing {
        println!("PROGRESS.md up to date ({done}/{steps} steps done)");
    } else {
        std::fs::write(&path, new)?;
        println!(
            "PROGRESS.md regenerated ({} phases, {done}/{steps} steps done)",
            phases.len()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const PHASE: &str = "# Phase 00 — Workspace\n\ntext\n\n### P00.S01 — First step\n- Crates: x\n\
                         ### P00.S02 — Second step\n### Not a step\n### P0.S1 — bad id\n";

    fn phases() -> Vec<Phase> {
        vec![parse_phase(PHASE)]
    }

    #[test]
    fn parses_step_headings() {
        let p = parse_phase(PHASE);
        assert_eq!(p.title, "Phase 00 — Workspace");
        assert_eq!(
            p.steps,
            vec![
                ("P00.S01".to_string(), "First step".to_string()),
                ("P00.S02".to_string(), "Second step".to_string()),
            ]
        );
    }

    #[test]
    fn preserves_ticks_and_notes() {
        let first = render(&phases(), "");
        assert!(first.contains("- [ ] P00.S01 — First step\n"));
        let ticked = first.replace(
            "- [ ] P00.S01 — First step",
            "- [x] P00.S01 — First step — 2026-09-23 — note — with dash",
        );
        let again = render(&phases(), &ticked);
        assert!(again.contains("- [x] P00.S01 — First step — 2026-09-23 — note — with dash\n"));
        assert!(again.contains("- [ ] P00.S02 — Second step\n"));
    }

    #[test]
    fn lists_removed_steps() {
        let old = "# Progress\n\n## Phase 00\n\n- [x] P00.S09 — Gone — 2026-01-01 — done\n\
                   - [ ] P00.S08 — Also gone\n";
        let out = render(&phases(), old);
        let removed = out.split(REMOVED).nth(1).expect("removed section");
        assert!(removed.contains("- [x] P00.S09 — Gone — 2026-01-01 — done"));
        assert!(removed.contains("- [ ] P00.S08 — Also gone"));
    }

    #[test]
    fn is_idempotent() {
        let old = "- [x] P00.S01 — Old title — 2026-09-23 — n\n- [x] P09.S09 — Removed — 2026-09-23 — r\n";
        let once = render(&phases(), old);
        let twice = render(&phases(), &once);
        assert_eq!(once, twice);
        // The title comes from the phase file, not from the old progress line.
        assert!(once.contains("- [x] P00.S01 — First step — 2026-09-23 — n"));
    }
}
