//! `cargo xtask style-props [--check]`: writes the table of every style property (name,
//! `style!` key, payload type, default, flags) to `crates/twine-style/PROPERTIES.md`, generated
//! from `twine_style::PROP_META`.
//!
//! `--check` fails when the committed file differs from the generated table.

use std::fmt::Write as _;

use twine_style::{PropFlags, PropId, StyleProp, StyleValue};

use crate::util::{R, workspace_root};

/// The generated file, relative to the workspace root.
pub const OUT: &str = "crates/twine-style/PROPERTIES.md";

/// Human-readable default of `id`.
fn default_text(id: PropId) -> String {
    let d = id.meta().default;
    match id {
        PropId::BorderSide => return "`BorderSide::FULL`".into(),
        PropId::TextDecor => return "none (`TextDecor::empty()`)".into(),
        _ => {}
    }
    match d {
        StyleValue::None => "none".into(),
        StyleValue::Font(_) => "theme font (`StyleDefaults::font`)".into(),
        StyleValue::Length(twine_style::Length::Px(v)) if v == twine_style::COORD_MAX => "`COORD_MAX`".into(),
        StyleValue::Enum(_) => match StyleProp::from_value(id, d) {
            // `Align(Default)` → `Default`; flag sets print their names.
            Some(p) => {
                let dbg = format!("{p:?}");
                let inner = dbg
                    .strip_prefix(id.name())
                    .and_then(|s| s.strip_prefix('('))
                    .and_then(|s| s.strip_suffix(')'))
                    .unwrap_or(&dbg);
                format!("`{inner}`")
            }
            None => d.to_string(),
        },
        StyleValue::Opa(o) => match o.0 {
            0 => "`Opa::TRANSP`".into(),
            255 => "`Opa::COVER`".into(),
            v => format!("`Opa({v})`"),
        },
        StyleValue::Scale(s) => format!("`Scale({})`", s.0),
        _ => format!("`{d}`"),
    }
}

fn flags_text(f: PropFlags) -> String {
    let names: Vec<&str> = f.iter_names().map(|(n, _)| n).collect();
    if names.is_empty() {
        "—".into()
    } else {
        names.join(", ")
    }
}

/// The markdown table.
#[must_use]
pub fn generate() -> String {
    let mut s = String::new();
    s.push_str("# Style properties\n\n");
    s.push_str(
        "<!-- generated by `cargo xtask style-props` from `twine_style::PROP_META`; do not edit -->\n\n",
    );
    let _ = writeln!(
        s,
        "All {} properties of `twine-style` (LVGL v9.6 `lv_style_prop_t`), in id order. \
         `style!` key = `StyleBuf` builder method. Flags are LVGL's \
         `LV_STYLE_PROP_FLAG_*`; the group is `id >> 4`.\n",
        twine_style::PROP_COUNT
    );
    s.push_str("| Id | Property | `style!` key | Type | Default | Flags | Group |\n");
    s.push_str("|---:|----------|--------------|------|---------|-------|------:|\n");
    for id in PropId::ALL {
        let m = id.meta();
        let _ = writeln!(
            s,
            "| {} | `{}` | `{}` | `{}` | {} | {} | {} |",
            id as u8,
            m.name,
            m.snake_name,
            m.type_name,
            default_text(id),
            flags_text(m.flags),
            m.group
        );
    }
    s
}

/// Writes the file, or with `check` compares it.
pub fn run(check: bool) -> R {
    let path = workspace_root().join(OUT);
    let want = generate();
    if check {
        let have = std::fs::read_to_string(&path).unwrap_or_default();
        if have != want {
            return Err(format!("style-props: {OUT} is out of date; run `cargo xtask style-props`").into());
        }
        println!("style-props: {OUT} is up to date");
        return Ok(());
    }
    std::fs::write(&path, want)?;
    println!("style-props: wrote {OUT}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_has_every_property() {
        let t = generate();
        assert_eq!(
            t.lines()
                .filter(|l| l.starts_with("| ") && !l.starts_with("| Id"))
                .count(),
            twine_style::PROP_COUNT
        );
        assert!(t.contains("| `Width` | `width` | `Length` | `content` | LAYOUT | 0 |"));
        assert!(t.contains("`Align` | `align` | `Align` | `Default` |"));
        assert!(t.contains("`TextFont` | `text_font` | `&'static Font` | theme font"));
    }
}
