//! `cargo xtask style-props [--check]`: writes the table of every style property (name,
//! key, payload type, default, flags, former names) and every shorthand to
//! `crates/twine-style/PROPERTIES.md`, generated from `twine_style::PROP_META`,
//! `twine_style::PROP_ALIASES` and `twine_style::SHORTHANDS` (all from the property table).
//!
//! `--check` fails when the committed file differs from the generated table.

use std::fmt::Write as _;

use twine_style::{PROP_ALIASES, PropFlags, PropId, SHORTHANDS, StyleProp, StyleValue};

use crate::util::{R, workspace_root};

/// The generated file, relative to the workspace root.
pub const OUT: &str = "crates/twine-style/PROPERTIES.md";

/// Human-readable default of `id`.
fn default_text(id: PropId) -> String {
    let d = id.meta().default;
    match id {
        PropId::BorderSide => return "`BorderSide::FULL`".into(),
        PropId::TextDecoration => return "none (`TextDecor::empty()`)".into(),
        _ => {}
    }
    match d {
        StyleValue::None => "none".into(),
        StyleValue::Font(_) => "theme font (`StyleDefaults::font`)".into(),
        StyleValue::Length(twine_style::Length::Px(v)) if v == twine_style::COORD_MAX => "`COORD_MAX`".into(),
        StyleValue::Enum(_) => match StyleProp::from_value(id, d) {
            // `Align(Default)` → `Default`; flag sets print their names.
            Some(p) => {
                let dbg = format!("{p:?}");
                let inner = dbg
                    .strip_prefix(id.name())
                    .and_then(|s| s.strip_prefix('('))
                    .and_then(|s| s.strip_suffix(')'))
                    .unwrap_or(&dbg);
                format!("`{inner}`")
            }
            None => d.to_string(),
        },
        StyleValue::Opa(o) => match o.raw() {
            0 => "`Opa::TRANSP`".into(),
            255 => "`Opa::COVER`".into(),
            v => format!("`Opa::from_raw({v})`"),
        },
        StyleValue::Scale(s) if s.raw_256() == 256 => "`Scale::ONE`".into(),
        StyleValue::Scale(s) => format!("`Scale::from_raw_256({})`", s.raw_256()),
        // Typed payloads stored compactly (ms / 1/255 / a pixel length): print the typed value.
        _ => match id.meta().type_name {
            "DurationMs" => format!("`Duration::ms({d})`"),
            "Fraction" => match d {
                StyleValue::Int(0) => "`Fraction::ZERO`".into(),
                StyleValue::Int(255) => "`Fraction::ONE`".into(),
                _ => format!("`Fraction::from_raw({d})`"),
            },
            "Radius" => match d.get::<twine_style::Radius>() {
                Some(r) => format!("`Radius::{r:?}`"),
                None => format!("`{d}`"),
            },
            _ => format!("`{d}`"),
        },
    }
}

fn flags_text(f: PropFlags) -> String {
    let names: Vec<&str> = f.iter_names().map(|(n, _)| n).collect();
    if names.is_empty() {
        "—".into()
    } else {
        names.join(", ")
    }
}

/// Former names as a markdown cell.
fn aliases_text(aliases: &[&str]) -> String {
    if aliases.is_empty() {
        "—".into()
    } else {
        aliases
            .iter()
            .map(|a| format!("`{a}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

/// The markdown tables.
#[must_use]
pub fn generate() -> String {
    let mut s = String::new();
    s.push_str("# Style properties\n\n");
    s.push_str(
        "<!-- generated by `cargo xtask style-props` from `twine_style::PROP_META`, `PROP_ALIASES` and \
         `SHORTHANDS`; do not edit -->\n\n",
    );
    let _ = writeln!(
        s,
        "All {} properties of `twine-style` (LVGL v9.6 `lv_style_prop_t`), in id order. Each has one \
         name, the **key**: the `style!` key, the `StyleBuf` builder method and the `twine-view` \
         modifier (`ViewExt`); the `PropId`/`StyleProp` variant is the same name in `PascalCase`. \
         The former names (the previous Twine key and the LVGL constant) are `#[doc(alias)]`es \
         only: `style!` rejects them. Flags are LVGL's `LV_STYLE_PROP_FLAG_*`; the group is \
         `id >> 4`.\n",
        twine_style::PROP_COUNT
    );
    s.push_str("| Id | Property | Key | Type | Default | Flags | Group | Former names |\n");
    s.push_str("|---:|----------|-----|------|---------|-------|------:|--------------|\n");
    for id in PropId::ALL {
        let m = id.meta();
        let _ = writeln!(
            s,
            "| {} | `{}` | `{}` | `{}` | {} | {} | {} | {} |",
            id as u8,
            m.name,
            m.snake_name,
            m.type_name,
            default_text(id),
            flags_text(m.flags),
            m.group,
            aliases_text(PROP_ALIASES[id as usize - 1])
        );
    }
    s.push_str("\n## Shorthands\n\n");
    s.push_str(
        "Shorthands set several properties at once and have the same name in `style!` (several \
         parameters are written as a tuple: `border: (1, Color::BLACK)`), `StyleBuf` and \
         `ViewExt`.\n\n",
    );
    s.push_str("| Shorthand | Parameters | Sets | Former names |\n");
    s.push_str("|-----------|------------|------|--------------|\n");
    for sh in SHORTHANDS {
        let params: Vec<String> = sh.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
        let mut props: Vec<&str> = Vec::new();
        for p in sh.props {
            let k = p.meta().snake_name;
            if !props.contains(&k) {
                props.push(k);
            }
        }
        let props: Vec<String> = props.iter().map(|k| format!("`{k}`")).collect();
        let _ = writeln!(
            s,
            "| `{}` | `{}` | {} | {} |",
            sh.name,
            params.join(", "),
            props.join(", "),
            aliases_text(sh.aliases)
        );
    }
    s
}

/// Writes the file, or with `check` compares it.
pub fn run(check: bool) -> R {
    let path = workspace_root().join(OUT);
    let want = generate();
    if check {
        let have = std::fs::read_to_string(&path).unwrap_or_default();
        if have != want {
            return Err(format!("style-props: {OUT} is out of date; run `cargo xtask style-props`").into());
        }
        println!("style-props: {OUT} is up to date");
        return Ok(());
    }
    std::fs::write(&path, want)?;
    println!("style-props: wrote {OUT}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_has_every_property() {
        let t = generate();
        assert_eq!(
            t.lines()
                .filter(|l| l.starts_with("| ") && l.as_bytes().get(2).is_some_and(u8::is_ascii_digit))
                .count(),
            twine_style::PROP_COUNT
        );
        assert!(t.contains("| `Width` | `width` | `Length` | `content` | LAYOUT | 0 | `LV_STYLE_WIDTH` |"));
        assert!(t.contains("`Align` | `align` | `Align` | `Default` |"));
        assert!(t.contains("`Font` | `font` | `&'static Font` | theme font"));
        assert!(t.contains("| `PaddingTop` | `padding_top` |"));
        assert!(t.contains("`pad_top`, `LV_STYLE_PAD_TOP`"));
        assert!(t.contains("| `padding` | `v: Length` | `padding_top`, `padding_bottom`, `padding_left`, `padding_right` | `pad_all` |"));
        assert!(t.contains(
            "| `border` | `width: Length, color: Color` | `border_width`, `border_color`, `border_opacity` | — |"
        ));
    }
}
