//! Rust source of a converted image.

use std::fmt::Write as _;

use twine_core::ColorFormat;
use twine_image::ImageHeader;

use super::CompressArg;

/// The Rust variant name of `f` (`ColorFormat::<name>`).
#[must_use]
pub fn variant(f: ColorFormat) -> &'static str {
    match f {
        ColorFormat::L8 => "L8",
        ColorFormat::A1 => "A1",
        ColorFormat::A2 => "A2",
        ColorFormat::A4 => "A4",
        ColorFormat::A8 => "A8",
        ColorFormat::I1 => "I1",
        ColorFormat::I2 => "I2",
        ColorFormat::I4 => "I4",
        ColorFormat::I8 => "I8",
        ColorFormat::Rgb565 => "Rgb565",
        ColorFormat::Rgb565Swapped => "Rgb565Swapped",
        ColorFormat::Rgb565A8 => "Rgb565A8",
        ColorFormat::Rgb888 => "Rgb888",
        ColorFormat::Argb8888 => "Argb8888",
        ColorFormat::Xrgb8888 => "Xrgb8888",
        ColorFormat::Argb8888Premultiplied => "Argb8888Premultiplied",
    }
}

/// Everything the source file mentions.
pub struct Emit<'a> {
    /// Static name.
    pub name: &'a str,
    /// Path of the crate that defines `Image` (e.g. `twine_image`).
    pub crate_path: &'a str,
    /// The command line that produced the file.
    pub command: &'a str,
    /// SHA-256 of the input file.
    pub input_sha256: &'a str,
    /// Header of the pixel data (with `COMPRESSED` set when compressed).
    pub header: ImageHeader,
    /// Compression.
    pub compress: CompressArg,
    /// File name of the sidecar data file.
    pub bin_name: &'a str,
    /// Bytes in the sidecar.
    pub stored_len: usize,
    /// Uncompressed size.
    pub data_len: usize,
}

/// The machine-readable summary line (also read by `twine image --info`).
#[must_use]
pub fn summary(e: &Emit<'_>) -> String {
    format!(
        "// twine-image: format={} w={} h={} stride={} flags={:#04x} compression={} stored={} size={}",
        e.header.format.name(),
        e.header.w,
        e.header.h,
        e.header.stride,
        e.header.flags.bits(),
        e.compress.name(),
        e.stored_len,
        e.data_len
    )
}

/// Renders the `.rs` file.
#[must_use]
pub fn render(e: &Emit<'_>) -> String {
    let c = e.crate_path;
    let mut s = String::new();
    let _ = writeln!(s, "// Generated by `twine image`; do not edit.");
    let _ = writeln!(s, "// Command: {}", e.command);
    let _ = writeln!(s, "// Input SHA-256: {}", e.input_sha256);
    let _ = writeln!(s, "{}", summary(e));
    let _ = writeln!(s);
    let header = format!(
        "{c}::ImageHeader {{\n        format: {c}::ColorFormat::{},\n        w: {},\n        h: {},\n        stride: {},\n        flags: {c}::ImageFlags::from_bits_retain({:#04x}),\n    }}",
        variant(e.header.format),
        e.header.w,
        e.header.h,
        e.header.stride,
        e.header.flags.bits()
    );
    let _ = writeln!(
        s,
        "/// `{}` ({}×{} `{}`).",
        e.name,
        e.header.w,
        e.header.h,
        e.header.format.name()
    );
    match e.compress {
        CompressArg::None => {
            let _ = writeln!(
                s,
                "pub static {}: {c}::Image = {c}::Image::new_static(\n    {header},\n    include_bytes!(\"{}\"),\n);",
                e.name, e.bin_name
            );
        }
        CompressArg::Rle | CompressArg::Lz4 => {
            let method = if e.compress == CompressArg::Rle {
                "Rle"
            } else {
                "Lz4"
            };
            let _ = writeln!(
                s,
                "pub static {}: {c}::Image = {c}::Image {{\n    header: {header},\n    data: {c}::ImageData::Compressed {{\n        method: {c}::Compression::{method},\n        data: include_bytes!(\"{}\"),\n        decompressed_size: {},\n    }},\n}};",
                e.name, e.bin_name, e.data_len
            );
        }
    }
    s
}
