//! [`BitmapFont`]: the built-in bitmap font format, with the same capabilities and semantics as
//! LVGL's `lv_font_fmt_txt_dsc_t` (cmaps, kerning, compression).

use core::sync::atomic::{AtomicBool, Ordering};

use crate::cache::GlyphCache;
use crate::decode::{decode_compressed, expand_row};
use crate::font::{GlyphInfo, GlyphProvider, provider_key};

/// Metrics and bitmap location of one glyph (LVGL `lv_font_fmt_txt_glyph_dsc_t`).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct GlyphDsc {
    /// Byte offset of the glyph's bitmap in [`BitmapFont::bitmap`].
    pub bitmap_index: u32,
    /// Advance width in 1/16 px.
    pub adv_w: u16,
    /// Bitmap width in px (subpixels for horizontal subpixel fonts).
    pub box_w: u8,
    /// Bitmap height in px (subpixels for vertical subpixel fonts).
    pub box_h: u8,
    /// Offset of the bitmap's left edge from the pen position.
    pub ofs_x: i8,
    /// Offset of the bitmap's bottom edge above the baseline.
    pub ofs_y: i8,
}

/// How a [`Cmap`] maps code points to glyph ids (LVGL `lv_font_fmt_txt_cmap_type_t`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum CmapKind {
    /// Contiguous range: `glyph_id_start + rcp`.
    Format0Tiny,
    /// Contiguous range with a per-code-point `u8` offset list; offset 0 (other than for the
    /// range's first code point) means "missing".
    Format0Full,
    /// Sparse code points (`unicode_list`, sorted): `glyph_id_start + index`.
    SparseTiny,
    /// Sparse code points with a `u16` offset list: `glyph_id_start + glyph_id_ofs_list[index]`.
    SparseFull,
}

/// Glyph id offsets of a [`Cmap`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum GlyphIdOfs {
    /// No offset list (`Format0Tiny`, `SparseTiny`).
    None,
    /// `u8` offsets (`Format0Full`).
    U8(&'static [u8]),
    /// `u16` offsets (`SparseFull`).
    U16(&'static [u16]),
}

/// A code point range mapped to glyph ids (LVGL `lv_font_fmt_txt_cmap_t`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct Cmap {
    /// First code point of the range.
    pub range_start: u32,
    /// Number of code points in the range.
    pub range_length: u16,
    /// Glyph id of the first mapped code point.
    pub glyph_id_start: u16,
    /// Sorted code points relative to `range_start` (sparse kinds).
    pub unicode_list: &'static [u16],
    /// Glyph id offsets (full kinds).
    pub glyph_id_ofs_list: GlyphIdOfs,
    /// Mapping kind.
    pub kind: CmapKind,
}

/// Sorted `[left, right]` glyph id pairs of pair kerning.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum KernPairIds {
    /// Glyph ids below 256.
    U8(&'static [[u8; 2]]),
    /// Any glyph ids.
    U16(&'static [[u16; 2]]),
}

/// Kerning data (values in 1/16 px before [`BitmapFont::kern_scale`]).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Kern {
    /// No kerning.
    None,
    /// A sorted list of glyph pairs and their values (LVGL `lv_font_fmt_txt_kern_pair_t`).
    Pairs {
        /// Pairs sorted lexicographically by `(left, right)`.
        glyph_ids: KernPairIds,
        /// One value per pair.
        values: &'static [i8],
    },
    /// Class-based kerning (LVGL `lv_font_fmt_txt_kern_classes_t`).
    Classes {
        /// Left class per glyph id (0 = no kerning).
        left_class_map: &'static [u8],
        /// Right class per glyph id (0 = no kerning).
        right_class_map: &'static [u8],
        /// `left_class_cnt × right_class_cnt` values, row-major by left class.
        class_pair_values: &'static [i8],
        /// Number of left classes.
        left_class_cnt: u8,
        /// Number of right classes.
        right_class_cnt: u8,
    },
}

/// How glyph bitmaps are stored.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum BitmapFormat {
    /// Bit-packed rows without padding.
    #[default]
    Plain,
    /// LVGL RLE with the XOR row prefilter.
    Compressed,
    /// LVGL RLE without the prefilter.
    CompressedNoPrefilter,
}

/// A bitmap font (LVGL `lv_font_fmt_txt_dsc_t`), normally generated by the font generator.
///
/// Glyph id 0 is reserved and means "missing".
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct BitmapFont {
    /// Bits per pixel of every glyph: 1, 2, 4 or 8.
    pub bpp: u8,
    /// All glyph bitmaps.
    pub bitmap: &'static [u8],
    /// Glyph descriptors indexed by glyph id (entry 0 is the reserved empty glyph).
    pub glyphs: &'static [GlyphDsc],
    /// Code point → glyph id maps, searched in order.
    pub cmaps: &'static [Cmap],
    /// Kerning.
    pub kern: Kern,
    /// Kerning scale in 12.4 fixed point (16 = 1.0).
    pub kern_scale: u16,
    /// Bitmap storage format.
    pub format: BitmapFormat,
}

static BAD_BPP_WARNED: AtomicBool = AtomicBool::new(false);

impl BitmapFont {
    /// The glyph id of `cp` (`None` when missing).
    #[must_use]
    pub fn glyph_id(&self, cp: char) -> Option<u16> {
        let cp = u32::from(cp);
        for c in self.cmaps {
            let Some(rcp) = cp.checked_sub(c.range_start) else {
                continue;
            };
            if rcp >= u32::from(c.range_length) {
                continue;
            }
            let id = match c.kind {
                CmapKind::Format0Tiny => u32::from(c.glyph_id_start) + rcp,
                CmapKind::Format0Full => {
                    let GlyphIdOfs::U8(ofs) = c.glyph_id_ofs_list else {
                        continue;
                    };
                    let Some(&o) = ofs.get(rcp as usize) else {
                        continue;
                    };
                    if o == 0 && rcp != 0 {
                        continue;
                    }
                    u32::from(c.glyph_id_start) + u32::from(o)
                }
                CmapKind::SparseTiny => {
                    let Ok(i) = c.unicode_list.binary_search(&(rcp as u16)) else {
                        continue;
                    };
                    u32::from(c.glyph_id_start) + i as u32
                }
                CmapKind::SparseFull => {
                    let Ok(i) = c.unicode_list.binary_search(&(rcp as u16)) else {
                        continue;
                    };
                    let GlyphIdOfs::U16(ofs) = c.glyph_id_ofs_list else {
                        continue;
                    };
                    let Some(&o) = ofs.get(i) else {
                        continue;
                    };
                    u32::from(c.glyph_id_start) + u32::from(o)
                }
            };
            return match u16::try_from(id) {
                Ok(0) | Err(_) => None,
                Ok(id) => Some(id),
            };
        }
        None
    }

    /// Raw kerning value between two glyph ids in 1/16 px, `kern_scale` applied
    /// (`(value × kern_scale) >> 4`, arithmetic shift).
    #[must_use]
    pub fn kern(&self, left: u16, right: u16) -> i32 {
        let v: i8 = match self.kern {
            Kern::None => 0,
            Kern::Pairs { glyph_ids, values } => {
                let idx = match glyph_ids {
                    KernPairIds::U8(pairs) => match (u8::try_from(left), u8::try_from(right)) {
                        (Ok(l), Ok(r)) => pairs.binary_search(&[l, r]).ok(),
                        _ => None,
                    },
                    KernPairIds::U16(pairs) => pairs.binary_search(&[left, right]).ok(),
                };
                idx.and_then(|i| values.get(i).copied()).unwrap_or(0)
            }
            Kern::Classes {
                left_class_map,
                right_class_map,
                class_pair_values,
                right_class_cnt,
                ..
            } => {
                let l = left_class_map.get(usize::from(left)).copied().unwrap_or(0);
                let r = right_class_map.get(usize::from(right)).copied().unwrap_or(0);
                if l > 0 && r > 0 {
                    let i = usize::from(l - 1) * usize::from(right_class_cnt) + usize::from(r - 1);
                    class_pair_values.get(i).copied().unwrap_or(0)
                } else {
                    0
                }
            }
        };
        (i32::from(v) * i32::from(self.kern_scale)) >> 4
    }

    fn valid_bpp(&self) -> bool {
        if matches!(self.bpp, 1 | 2 | 4 | 8) {
            return true;
        }
        debug_assert!(false, "invalid bitmap font bpp {}", self.bpp);
        if !BAD_BPP_WARNED.load(Ordering::Relaxed) {
            BAD_BPP_WARNED.store(true, Ordering::Relaxed);
            twine_core::warn!(target: "twine::text", "bitmap font with invalid bpp {}; glyphs treated as missing", self.bpp);
        }
        false
    }

    fn dsc(&self, info: &GlyphInfo) -> Option<&GlyphDsc> {
        let d = self.glyphs.get(info.id as usize)?;
        (u16::from(d.box_w) == info.box_w && u16::from(d.box_h) == info.box_h).then_some(d)
    }

    fn warn_corrupt(&self, cache: &mut GlyphCache) {
        let key = provider_key(self);
        if cache.first_warning((key, u32::MAX)) {
            twine_core::warn!(target: "twine::text", "corrupt glyph data in bitmap font at {:#x}", key);
        }
    }

    /// Streams rows of the glyph (`sink(y, a8_row)`); the shared core of both render paths.
    fn rows(&self, info: &GlyphInfo, cache: &mut GlyphCache, sink: &mut dyn FnMut(usize, &[u8])) -> bool {
        if !self.valid_bpp() {
            return false;
        }
        let Some(d) = self.dsc(info) else {
            return false;
        };
        let (w, h) = (usize::from(d.box_w), usize::from(d.box_h));
        if w == 0 || h == 0 {
            return true;
        }
        let start = d.bitmap_index as usize;
        let Some(data) = self.bitmap.get(start..) else {
            self.warn_corrupt(cache);
            return false;
        };
        let bpp = self.bpp;
        match self.format {
            BitmapFormat::Plain if bpp == 8 => {
                if data.len() < w * h {
                    self.warn_corrupt(cache);
                    return false;
                }
                for (y, row) in data.chunks_exact(w).take(h).enumerate() {
                    sink(y, row);
                }
                true
            }
            BitmapFormat::Plain => {
                let mut row = core::mem::take(&mut cache.row_a);
                let mut ok = true;
                for y in 0..h {
                    ok &= expand_row(data, y * w * usize::from(bpp), bpp, w, &mut row);
                    sink(y, &row[..w]);
                }
                cache.row_a = row;
                if !ok {
                    self.warn_corrupt(cache);
                }
                ok
            }
            BitmapFormat::Compressed | BitmapFormat::CompressedNoPrefilter => {
                let prefilter = self.format == BitmapFormat::Compressed;
                let key = (provider_key(self), info.id);
                if let Some(bmp) = cache.get(key) {
                    for (y, row) in bmp.chunks_exact(w).take(h).enumerate() {
                        sink(y, row);
                    }
                    return true;
                }
                twine_core::trace!(target: "twine::text", "glyph cache miss font={:#x} id={}", key.0, info.id);
                let mut a = core::mem::take(&mut cache.row_a);
                let mut b = core::mem::take(&mut cache.row_b);
                let ok = if let Some(slot) = cache.insert(key, w, h) {
                    let ok = decode_compressed(data, bpp, w, h, prefilter, &mut a, &mut b, &mut |y, r| {
                        slot[y * w..(y + 1) * w].copy_from_slice(r);
                    });
                    if ok {
                        for (y, row) in slot.chunks_exact(w).enumerate() {
                            sink(y, row);
                        }
                    }
                    ok
                } else {
                    decode_compressed(data, bpp, w, h, prefilter, &mut a, &mut b, sink)
                };
                cache.row_a = a;
                cache.row_b = b;
                if !ok {
                    cache.remove(key);
                    self.warn_corrupt(cache);
                }
                ok
            }
        }
    }
}

impl GlyphProvider for BitmapFont {
    fn glyph_info(&self, cp: char, next: Option<char>) -> Option<GlyphInfo> {
        if !self.valid_bpp() {
            return None;
        }
        let id = self.glyph_id(cp)?;
        let d = self.glyphs.get(usize::from(id))?;
        let kern = match (self.kern, next) {
            (Kern::None, _) | (_, None) => 0,
            (_, Some(n)) => self.glyph_id(n).map_or(0, |nid| self.kern(id, nid)),
        };
        let adv = (i32::from(d.adv_w) + kern).clamp(0, i32::from(u16::MAX));
        Some(GlyphInfo {
            adv_w: adv as u16,
            box_w: u16::from(d.box_w),
            box_h: u16::from(d.box_h),
            ofs_x: i16::from(d.ofs_x),
            ofs_y: i16::from(d.ofs_y),
            bpp: self.bpp,
            id: u32::from(id),
            is_placeholder: false,
        })
    }

    fn render_a8(&self, info: &GlyphInfo, out: &mut [u8], cache: &mut GlyphCache) -> bool {
        let w = usize::from(info.box_w);
        let n = w * usize::from(info.box_h);
        if out.len() < n {
            debug_assert!(
                false,
                "render_a8: output buffer of {} bytes for a {}-byte glyph",
                out.len(),
                n
            );
            return false;
        }
        self.rows(info, cache, &mut |y, row| {
            out[y * w..(y + 1) * w].copy_from_slice(row);
        })
    }

    fn render_rows(
        &self,
        info: &GlyphInfo,
        cache: &mut GlyphCache,
        sink: &mut dyn FnMut(usize, &[u8]),
    ) -> bool {
        self.rows(info, cache, sink)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::font::{FALLBACK_CYCLE_WARNED, Font, Subpx};
    use crate::test_font::*;

    #[test]
    fn format0_tiny_maps_contiguous_range() {
        let f = &TEST_BITMAP;
        assert_eq!(f.glyph_id('A'), Some(1));
        assert_eq!(f.glyph_id('B'), Some(2));
        assert_eq!(f.glyph_id('C'), Some(3));
        assert_eq!(f.glyph_id('D'), None);
        assert_eq!(f.glyph_id('@'), None);
    }

    #[test]
    fn format0_full_zero_offset_is_missing() {
        static OFS: [u8; 4] = [0, 1, 0, 2];
        static CMAPS: [Cmap; 1] = [Cmap {
            range_start: 0x30,
            range_length: 4,
            glyph_id_start: 1,
            unicode_list: &[],
            glyph_id_ofs_list: GlyphIdOfs::U8(&OFS),
            kind: CmapKind::Format0Full,
        }];
        let f = BitmapFont {
            cmaps: &CMAPS,
            ..TEST_BITMAP
        };
        assert_eq!(f.glyph_id('0'), Some(1), "offset 0 at the range start is valid");
        assert_eq!(f.glyph_id('1'), Some(2));
        assert_eq!(f.glyph_id('2'), None);
        assert_eq!(f.glyph_id('3'), Some(3));
    }

    #[test]
    fn sparse_tiny_binary_search_hits_and_misses() {
        let f = &TEST_BITMAP;
        // Sparse cmap starts at U+00B0 with list [0, 0x1F72] → '°' and '•'.
        assert_eq!(f.glyph_id('°'), Some(4));
        assert_eq!(f.glyph_id('•'), Some(5));
        assert_eq!(f.glyph_id('±'), None);
    }

    #[test]
    fn sparse_full_uses_offset_list() {
        static LIST: [u16; 3] = [0, 5, 9];
        static OFS: [u16; 3] = [2, 0, 1];
        static CMAPS: [Cmap; 1] = [Cmap {
            range_start: 0x100,
            range_length: 10,
            glyph_id_start: 1,
            unicode_list: &LIST,
            glyph_id_ofs_list: GlyphIdOfs::U16(&OFS),
            kind: CmapKind::SparseFull,
        }];
        let f = BitmapFont {
            cmaps: &CMAPS,
            ..TEST_BITMAP
        };
        assert_eq!(f.glyph_id('\u{100}'), Some(3));
        assert_eq!(f.glyph_id('\u{105}'), Some(1));
        assert_eq!(f.glyph_id('\u{109}'), Some(2));
        assert_eq!(f.glyph_id('\u{104}'), None);
    }

    #[test]
    fn kern_pairs_u8_and_u16_lookup() {
        static P16: [[u16; 2]; 2] = [[1, 300], [300, 2]];
        static V: [i8; 2] = [5, -7];
        let f = &TEST_BITMAP; // pairs (1,2) = -16, (2,1) = 8
        assert_eq!(f.kern(1, 2), -16);
        assert_eq!(f.kern(2, 1), 8);
        assert_eq!(f.kern(1, 3), 0);
        let f16 = BitmapFont {
            kern: Kern::Pairs {
                glyph_ids: KernPairIds::U16(&P16),
                values: &V,
            },
            ..TEST_BITMAP
        };
        assert_eq!(f16.kern(1, 300), 5);
        assert_eq!(f16.kern(300, 2), -7);
        assert_eq!(f16.kern(2, 300), 0);
        // U8 pairs never match ids ≥ 256.
        assert_eq!(f.kern(1, 300), 0);
    }

    #[test]
    fn kern_classes_lookup_and_zero_class_means_none() {
        static L: [u8; 4] = [0, 1, 2, 0];
        static R: [u8; 4] = [0, 2, 1, 1];
        // 2 left × 2 right classes.
        static VALS: [i8; 4] = [1, 2, 3, 4];
        let f = BitmapFont {
            kern: Kern::Classes {
                left_class_map: &L,
                right_class_map: &R,
                class_pair_values: &VALS,
                left_class_cnt: 2,
                right_class_cnt: 2,
            },
            ..TEST_BITMAP
        };
        assert_eq!(f.kern(1, 1), 2); // l1, r2 → [0 * 2 + 1]
        assert_eq!(f.kern(2, 2), 3); // l2, r1 → [1 * 2 + 0]
        assert_eq!(f.kern(2, 1), 4);
        assert_eq!(f.kern(3, 1), 0, "left class 0");
        assert_eq!(f.kern(1, 0), 0, "right class 0");
        assert_eq!(f.kern(1, 99), 0, "out of range");
    }

    #[test]
    fn kern_scale_applied_with_shift() {
        static P: [[u8; 2]; 2] = [[1, 2], [2, 1]];
        static V: [i8; 2] = [8, -3];
        let mut f = BitmapFont {
            kern: Kern::Pairs {
                glyph_ids: KernPairIds::U8(&P),
                values: &V,
            },
            kern_scale: 16,
            ..TEST_BITMAP
        };
        assert_eq!(f.kern(1, 2), 8);
        f.kern_scale = 24;
        assert_eq!(f.kern(2, 1), -5, "-3 × 24 = -72 >> 4 = -4.5 → floors to -5");
    }

    #[test]
    fn advance_px_rounds_like_lvgl() {
        // Glyphs A/B/C have adv 7, 8, 24 (1/16 px).
        let f = &TEST_FONT;
        assert_eq!(f.advance_px('A', None), 0);
        assert_eq!(f.advance_px('B', None), 1);
        assert_eq!(f.advance_px('C', None), 2);
        // Kerning A→B is -16: 7 - 16 clamps to 0.
        assert_eq!(f.advance_px('A', Some('B')), 0);
        // B→A is +8: 16 → 1.
        assert_eq!(f.advance_px('B', Some('A')), 1);
        assert_eq!(f.glyph('B', Some('A')).unwrap().1.adv_w, 16);
    }

    #[test]
    fn tab_is_two_spaces() {
        let f = &TEST_FONT; // space adv = 64 (4 px)
        assert_eq!(f.advance_px(' ', None), 4);
        assert_eq!(f.advance_px('\t', Some('A')), 8);
    }

    #[test]
    fn newline_has_zero_advance() {
        let f = &TEST_FONT;
        assert_eq!(f.advance_px('\n', None), 0);
        assert_eq!(f.advance_px('\r', Some('\n')), 0);
        assert!(f.glyph('\n', None).is_none());
        // Missing printable character: LVGL placeholder width line_height/2 + 2.
        assert_eq!(f.advance_px('Z', None), 10 / 2 + 2);
        assert_eq!(f.advance_px('\u{F8FF}', None), 0, "DUMMY symbol is invisible");
    }

    #[test]
    fn fallback_chain_used_when_primary_missing() {
        static SECOND: Font = Font {
            line_height: 10,
            base_line: 2,
            underline_position: -1,
            underline_thickness: 1,
            provider: &TEST_BITMAP,
            fallback: None,
            subpx: Subpx::None,
        };
        static EMPTY_BITMAP: BitmapFont = BitmapFont {
            cmaps: &[],
            ..TEST_BITMAP
        };
        static FIRST: Font = Font {
            provider: &EMPTY_BITMAP,
            fallback: Some(&SECOND),
            ..SECOND
        };
        let (font, info) = FIRST.glyph('C', None).unwrap();
        assert!(core::ptr::eq(font, &raw const SECOND));
        assert_eq!(info.id, 3);
        assert_eq!(FIRST.advance_px('C', None), 2);
    }

    #[test]
    fn fallback_cycle_is_cut_and_logged() {
        static EMPTY_BITMAP: BitmapFont = BitmapFont {
            cmaps: &[],
            ..TEST_BITMAP
        };
        static A: Font = Font {
            line_height: 10,
            base_line: 2,
            underline_position: -1,
            underline_thickness: 1,
            provider: &EMPTY_BITMAP,
            fallback: Some(&B),
            subpx: Subpx::None,
        };
        static B: Font = Font {
            fallback: Some(&A),
            ..A
        };
        assert!(A.glyph('x', None).is_none());
        assert!(FALLBACK_CYCLE_WARNED.load(Ordering::Relaxed));
    }

    #[test]
    fn render_plain_4bpp_glyph() {
        let mut cache = GlyphCache::new(0);
        let info = TEST_BITMAP.glyph_info('A', None).unwrap();
        let mut out = [0u8; 6];
        assert!(TEST_BITMAP.render_a8(&info, &mut out, &mut cache));
        assert_eq!(out, [0, 255, 0, 17 * 8, 255, 17]);
    }
}
