//! The font model: [`Font`], [`GlyphProvider`] and [`GlyphInfo`].

use core::sync::atomic::{AtomicBool, Ordering};

use twine_render::ImagePixels;

use crate::cache::GlyphCache;

/// Subpixel rendering of a font's glyphs (LVGL `lv_font_subpx_t`).
///
/// Subpixel fonts store three coverage values per pixel (one per color channel) so text is
/// sharper on panels with a known subpixel layout.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Subpx {
    /// Ordinary grayscale anti-aliasing.
    #[default]
    None,
    /// Horizontal subpixels (R, G, B side by side): glyph boxes are three times as wide.
    Hor,
    /// Vertical subpixels (R, G, B stacked): glyph boxes are three times as tall.
    Ver,
}

/// Metrics of one glyph, as returned by [`GlyphProvider::glyph_info`].
///
/// Box offsets use LVGL's convention: `ofs_x` is the distance from the pen position to the
/// box's left edge, `ofs_y` the distance from the baseline **up** to the box's bottom edge.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct GlyphInfo {
    /// Advance width in 1/16 px, kerning with the next character included.
    pub adv_w: u16,
    /// Bitmap width in px (in subpixels for [`Subpx::Hor`] fonts).
    pub box_w: u16,
    /// Bitmap height in px (in subpixels for [`Subpx::Ver`] fonts).
    pub box_h: u16,
    /// Horizontal offset of the bitmap from the pen position.
    pub ofs_x: i16,
    /// Vertical offset of the bitmap's bottom edge above the baseline.
    pub ofs_y: i16,
    /// Bits per pixel of the stored bitmap (1, 2, 4 or 8), or 0 for an image glyph drawn from
    /// [`GlyphProvider::glyph_image`] (image fonts, LVGL `imgfont`).
    pub bpp: u8,
    /// Provider-specific glyph id (the glyph index for [`BitmapFont`](crate::BitmapFont)).
    pub id: u32,
    /// `true` for a replacement glyph drawn when a character is missing.
    pub is_placeholder: bool,
}

impl GlyphInfo {
    /// The advance in whole pixels, rounded like LVGL: `(adv_w + 8) >> 4`.
    ///
    /// ```
    /// use twine_text::GlyphInfo;
    /// let g = GlyphInfo { adv_w: 24, ..GlyphInfo::default() };
    /// assert_eq!(g.advance_px(), 2);
    /// ```
    #[must_use]
    pub const fn advance_px(&self) -> i32 {
        (self.adv_w as i32 + 8) >> 4
    }
}

/// Source of glyph metrics and coverage bitmaps: a [`BitmapFont`](crate::BitmapFont), a
/// runtime TrueType font (feature `ttf`) or an [`ImageFontProvider`](crate::ImageFontProvider).
///
/// Implementations are `Sync` because fonts are `static`s shared by the whole program.
pub trait GlyphProvider: Sync {
    /// Metrics of `cp`, with kerning against `next` included in `adv_w` (only when `next` is
    /// also provided by this provider). `None` when the character is missing: the caller then
    /// tries the font's fallback and finally draws a replacement box.
    fn glyph_info(&self, cp: char, next: Option<char>) -> Option<GlyphInfo>;

    /// Writes the glyph's A8 coverage (`box_w × box_h`, stride `box_w`) into `out`.
    ///
    /// Returns `false` (and leaves `out` unspecified) when `out` is too small or the glyph data
    /// is corrupt. May use `cache` to keep decoded bitmaps.
    fn render_a8(&self, info: &GlyphInfo, out: &mut [u8], cache: &mut GlyphCache) -> bool;

    /// Streams the glyph's A8 coverage row by row to `sink(row_index, row)` (each row
    /// `box_w` bytes). Returns `false` if the glyph could not be decoded.
    ///
    /// The default implementation renders the whole glyph with
    /// [`render_a8`](Self::render_a8) into the cache's glyph scratch buffer; providers that can
    /// decode incrementally override it to avoid the copy.
    fn render_rows(
        &self,
        info: &GlyphInfo,
        cache: &mut GlyphCache,
        sink: &mut dyn FnMut(usize, &[u8]),
    ) -> bool {
        let w = usize::from(info.box_w);
        let h = usize::from(info.box_h);
        let Some(mut buf) = cache.take_glyph_scratch(w * h) else {
            return false;
        };
        let ok = self.render_a8(info, &mut buf, cache);
        if ok && w > 0 {
            for (y, row) in buf.chunks_exact(w).take(h).enumerate() {
                sink(y, row);
            }
        }
        cache.put_glyph_scratch(buf);
        ok
    }

    /// The image of an image glyph (one whose [`GlyphInfo::bpp`] is 0), drawn instead of A8
    /// coverage. `cp` and `next` are the arguments `glyph_info` was called with. The default
    /// (coverage-only providers) returns `None`.
    fn glyph_image(&self, cp: char, next: Option<char>) -> Option<&'static ImagePixels<'static>> {
        let _ = (cp, next);
        None
    }
}

/// A font: line metrics plus a [`GlyphProvider`] and an optional fallback font.
///
/// Built-in fonts are `static`s generated by the font generator (see the `twine-assets` crate);
/// every method that walks the fallback chain therefore takes `&'static self`.
///
/// Vertical metrics follow LVGL: a line is `line_height` px tall and the baseline lies
/// `base_line` px above the line's bottom, so it is [`ascent`](Self::ascent) px below the top.
pub struct Font {
    /// Height of one line in px.
    pub line_height: i16,
    /// Distance of the baseline from the bottom of the line in px.
    pub base_line: i16,
    /// Underline position relative to the baseline (negative = below the baseline).
    pub underline_position: i8,
    /// Underline thickness in px (0 is drawn as 1).
    pub underline_thickness: u8,
    /// Glyph metrics and bitmaps.
    pub provider: &'static dyn GlyphProvider,
    /// Font consulted for characters the provider lacks.
    pub fallback: Option<&'static Font>,
    /// Subpixel layout of the glyph bitmaps.
    pub subpx: Subpx,
}

impl core::fmt::Debug for Font {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("Font")
            .field("addr", &core::ptr::from_ref(self))
            .field("line_height", &self.line_height)
            .field("base_line", &self.base_line)
            .field("subpx", &self.subpx)
            .field("has_fallback", &self.fallback.is_some())
            .finish_non_exhaustive()
    }
}

/// Maximum number of fonts consulted for one character (the font plus 7 fallbacks). Longer
/// chains are assumed to be cycles: they are cut and logged once.
pub const MAX_FALLBACK_DEPTH: usize = 8;

/// Set once the fallback-chain guard fired (the warning is logged only once per program).
pub(crate) static FALLBACK_CYCLE_WARNED: AtomicBool = AtomicBool::new(false);

/// Provider of [`EMPTY_FONT`]: has no glyphs.
struct EmptyProvider;

impl GlyphProvider for EmptyProvider {
    fn glyph_info(&self, _cp: char, _next: Option<char>) -> Option<GlyphInfo> {
        None
    }

    fn render_a8(&self, _info: &GlyphInfo, _out: &mut [u8], _cache: &mut GlyphCache) -> bool {
        false
    }
}

/// A font without glyphs and with zero line height: the style default when no theme font is
/// supplied. Every character is drawn as a (tiny) replacement box.
pub static EMPTY_FONT: Font = Font {
    line_height: 0,
    base_line: 0,
    underline_position: 0,
    underline_thickness: 0,
    provider: &EmptyProvider,
    fallback: None,
    subpx: Subpx::None,
};

impl Font {
    /// Resolves `cp` through this font, then its fallback chain; returns the font that has it
    /// and the glyph's metrics.
    ///
    /// `'\t'` resolves to the space glyph with twice its advance (LVGL); `'\n'` and `'\r'`
    /// have no glyph. Kerning against `next` is applied only when `next` comes from the same
    /// font as `cp`. The chain is walked at most [`MAX_FALLBACK_DEPTH`] levels.
    pub fn glyph(&'static self, cp: char, next: Option<char>) -> Option<(&'static Font, GlyphInfo)> {
        if matches!(cp, '\n' | '\r') {
            return None;
        }
        let tab = cp == '\t';
        let (look, next) = if tab { (' ', None) } else { (cp, next) };
        let mut font = self;
        for _ in 0..MAX_FALLBACK_DEPTH {
            if let Some(mut info) = font.provider.glyph_info(look, next) {
                if tab {
                    info.adv_w = info.adv_w.saturating_mul(2);
                    info.box_w = info.box_w.saturating_mul(2);
                }
                return Some((font, info));
            }
            font = font.fallback?;
        }
        // Load + store instead of `swap`: thumbv6m has no atomic read-modify-write.
        if !FALLBACK_CYCLE_WARNED.load(Ordering::Relaxed) {
            FALLBACK_CYCLE_WARNED.store(true, Ordering::Relaxed);
            twine_core::warn!(
                target: "twine::text",
                "font fallback chain longer than {} fonts (cycle?); lookup of U+{:04X} stopped",
                MAX_FALLBACK_DEPTH,
                u32::from(cp)
            );
        }
        None
    }

    /// Advance of `cp` in whole pixels (LVGL rounding), including kerning with `next`.
    ///
    /// `'\t'` is two spaces wide; `'\n'`/`'\r'` have zero advance. A character that no font
    /// in the chain provides advances by the width of the replacement box plus 2 px, like
    /// LVGL's placeholder glyph; characters without a placeholder ([`has_placeholder`]) advance 0.
    pub fn advance_px(&'static self, cp: char, next: Option<char>) -> i32 {
        match self.glyph(cp, next) {
            Some((_, g)) => g.advance_px(),
            None if !has_placeholder(cp) => 0,
            None => self.placeholder_width() + 2,
        }
    }

    /// Distance from the top of a line to the baseline: `line_height - base_line`.
    #[must_use]
    pub const fn ascent(&self) -> i32 {
        self.line_height as i32 - self.base_line as i32
    }

    /// Width of the replacement box drawn for missing characters: `line_height / 2`.
    #[must_use]
    pub const fn placeholder_width(&self) -> i32 {
        self.line_height as i32 / 2
    }

    /// The glyph provider's address, used as the glyph-cache key of this font's provider.
    #[must_use]
    pub fn provider_key(&self) -> usize {
        provider_key(self.provider)
    }
}

/// Whether a character missing from every font is drawn as a replacement box (LVGL rule): not
/// for control characters (below U+0020), U+F8FF (`symbols::DUMMY`) and U+200C (zero-width
/// non-joiner), which stay invisible and take no space.
#[must_use]
pub const fn has_placeholder(cp: char) -> bool {
    !matches!(cp as u32, 0..=0x1F | 0xF8FF | 0x200C)
}

/// Glyph-cache key of a provider: its address.
#[must_use]
pub fn provider_key(p: &dyn GlyphProvider) -> usize {
    core::ptr::from_ref(p).cast::<()>() as usize
}
