// Generated by twine-cli 0.1.0: twine font --ttf assets/fonts/unscii-8.ttf --size 8 --bpp 1 --range 0x20-0x7F --no-kerning --name UNSCII_8 --out crates/twine-assets/src/fonts/unscii_8.rs
// Source: unscii-8.ttf SHA-256 97a4eea8cfede2b57b3ce0f3fa111335edde58bc8b07b8670737351468a2c587
// 96 glyphs, line height 8 px, base line 0 px, 1 bpp, plain bitmaps, 0 kerning pairs.
// Do not edit: regenerate with the command above.

#[rustfmt::skip]
static UNSCII_8_BITMAP: [u8; 485] = [
    0xff, 0xcc, 0xcf, 0x3c, 0xc0, 0x6c, 0xdb, 0xfb, 0x6f, 0xed, 0x9b, 0x00, 0x31, 0xfc, 0x1e, 0x0f,
    0xe3, 0x00, 0xc7, 0x98, 0x61, 0x86, 0x78, 0xc0, 0x38, 0xd8, 0xe3, 0xbd, 0xd9, 0x9d, 0x80, 0x6f,
    0x00, 0x36, 0xcc, 0xc6, 0x30, 0xc6, 0x33, 0x36, 0xc0, 0x66, 0x3c, 0xff, 0x3c, 0x66, 0x30, 0xcf,
    0xcc, 0x30, 0x6f, 0x00, 0xfc, 0xf0, 0x03, 0x06, 0x0c, 0x18, 0x30, 0x60, 0xc0, 0x7b, 0x3d, 0xfb,
    0xcf, 0x37, 0x80, 0x31, 0xc3, 0x0c, 0x30, 0xcf, 0xc0, 0x7b, 0x31, 0x8c, 0x63, 0x0f, 0xc0, 0x7b,
    0x30, 0xce, 0x0f, 0x37, 0x80, 0x1c, 0x79, 0xb6, 0x6f, 0xe1, 0x83, 0x00, 0xff, 0x0f, 0x83, 0x0f,
    0x37, 0x80, 0x39, 0x8c, 0x3e, 0xcf, 0x37, 0x80, 0xfc, 0x30, 0xc6, 0x30, 0xc3, 0x00, 0x7b, 0x3c,
    0xde, 0xcf, 0x37, 0x80, 0x7b, 0x3c, 0xdf, 0x0c, 0x67, 0x00, 0xf0, 0xf0, 0x6c, 0x06, 0xf0, 0x19,
    0x99, 0x86, 0x18, 0x60, 0xfc, 0x0f, 0xc0, 0xc3, 0x0c, 0x33, 0x33, 0x00, 0x7b, 0x30, 0xc6, 0x30,
    0x03, 0x00, 0x7d, 0x8f, 0x7e, 0xfd, 0xf8, 0x1f, 0x00, 0x31, 0xec, 0xf3, 0xff, 0x3c, 0xc0, 0xfb,
    0x3c, 0xfe, 0xcf, 0x3f, 0x80, 0x7b, 0x3c, 0x30, 0xc3, 0x37, 0x80, 0xf3, 0x6c, 0xf3, 0xcf, 0x6f,
    0x00, 0xff, 0x0c, 0x3e, 0xc3, 0x0f, 0xc0, 0xff, 0x0c, 0x3e, 0xc3, 0x0c, 0x00, 0x7b, 0x3c, 0x37,
    0xcf, 0x37, 0xc0, 0xcf, 0x3c, 0xff, 0xcf, 0x3c, 0xc0, 0xfc, 0xc3, 0x0c, 0x30, 0xcf, 0xc0, 0x0c,
    0x30, 0xc3, 0x0f, 0x37, 0x80, 0xc7, 0x9b, 0x67, 0x8d, 0x99, 0xb1, 0x80, 0xc3, 0x0c, 0x30, 0xc3,
    0x0f, 0xc0, 0xc7, 0xdf, 0xfe, 0xbc, 0x78, 0xf1, 0x80, 0xc7, 0xcf, 0xde, 0xfc, 0xf8, 0xf1, 0x80,
    0x7b, 0x3c, 0xf3, 0xcf, 0x37, 0x80, 0xfb, 0x3c, 0xfe, 0xc3, 0x0c, 0x00, 0x7b, 0x3c, 0xf3, 0xcf,
    0x66, 0xc0, 0xfb, 0x3c, 0xfe, 0xdb, 0x3c, 0xc0, 0x7b, 0x3c, 0x1e, 0x0f, 0x37, 0x80, 0xfc, 0xc3,
    0x0c, 0x30, 0xc3, 0x00, 0xcf, 0x3c, 0xf3, 0xcf, 0x37, 0x80, 0xcf, 0x3c, 0xf3, 0xcd, 0xe3, 0x00,
    0xc7, 0x8f, 0x1e, 0xbf, 0xfd, 0xf1, 0x80, 0xc3, 0x66, 0x3c, 0x18, 0x3c, 0x66, 0xc3, 0xc3, 0x66,
    0x3c, 0x18, 0x18, 0x18, 0x18, 0xfc, 0x31, 0x8c, 0x63, 0x0f, 0xc0, 0xfc, 0xcc, 0xcc, 0xf0, 0xc0,
    0x60, 0x30, 0x18, 0x0c, 0x06, 0x03, 0xf3, 0x33, 0x33, 0xf0, 0x10, 0x71, 0xb6, 0x30, 0xff, 0xc6,
    0x30, 0x78, 0x37, 0xf3, 0x7c, 0xc3, 0x0f, 0xb3, 0xcf, 0x3f, 0x80, 0x7e, 0x31, 0x87, 0x80, 0x0c,
    0x37, 0xf3, 0xcf, 0x37, 0xc0, 0x7b, 0x3f, 0xf0, 0x78, 0x3b, 0x3e, 0xc6, 0x31, 0x80, 0x7f, 0x3c,
    0xdf, 0x0f, 0xe0, 0xc3, 0x0f, 0xb3, 0xcf, 0x3c, 0xc0, 0x60, 0x38, 0xc6, 0x31, 0xe0, 0x18, 0x06,
    0x31, 0x8c, 0x7e, 0xc3, 0x0c, 0xf6, 0xf3, 0x6c, 0xc0, 0xe3, 0x18, 0xc6, 0x31, 0xe0, 0xcd, 0xff,
    0x5e, 0xbc, 0x60, 0xfb, 0x3c, 0xf3, 0xcc, 0x7b, 0x3c, 0xf3, 0x78, 0xfb, 0x3c, 0xfe, 0xc3, 0x00,
    0x7f, 0x3c, 0xdf, 0x0c, 0x30, 0xfb, 0x3c, 0x30, 0xc0, 0x7f, 0x07, 0x83, 0xf8, 0x61, 0x8f, 0xd8,
    0x61, 0x83, 0xc0, 0xcf, 0x3c, 0xf3, 0x7c, 0xcf, 0x3c, 0xde, 0x30, 0xc7, 0x8f, 0x5b, 0xe6, 0xc0,
    0xc6, 0xd8, 0xe3, 0x6c, 0x60, 0xcf, 0x3c, 0xdf, 0x0d, 0xe0, 0xfc, 0x63, 0x18, 0xfc, 0x1c, 0xc3,
    0x38, 0x30, 0xc1, 0xc0, 0xff, 0xfc, 0xe0, 0xc3, 0x07, 0x30, 0xce, 0x00, 0x77, 0xb8, 0xc1, 0x42,
    0xbd, 0x2c, 0x40, 0x81, 0x00,
];

#[rustfmt::skip]
static UNSCII_8_GLYPHS: [twine_text::GlyphDsc; 97] = [
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 0, box_w: 0, box_h: 0, ofs_x: 0, ofs_y: 0 }, // reserved
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 128, box_w: 0, box_h: 0, ofs_x: 0, ofs_y: 0 }, // U+0020 ' '
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 128, box_w: 2, box_h: 7, ofs_x: 3, ofs_y: 1 }, // U+0021 '!'
    twine_text::GlyphDsc { bitmap_index: 2, adv_w: 128, box_w: 6, box_h: 3, ofs_x: 1, ofs_y: 5 }, // U+0022 '"'
    twine_text::GlyphDsc { bitmap_index: 5, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0023 '#'
    twine_text::GlyphDsc { bitmap_index: 12, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0024 '$'
    twine_text::GlyphDsc { bitmap_index: 18, adv_w: 128, box_w: 7, box_h: 6, ofs_x: 0, ofs_y: 1 }, // U+0025 '%'
    twine_text::GlyphDsc { bitmap_index: 24, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0026 '&'
    twine_text::GlyphDsc { bitmap_index: 31, adv_w: 128, box_w: 3, box_h: 3, ofs_x: 2, ofs_y: 5 }, // U+0027 '\''
    twine_text::GlyphDsc { bitmap_index: 33, adv_w: 128, box_w: 4, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+0028 '('
    twine_text::GlyphDsc { bitmap_index: 37, adv_w: 128, box_w: 4, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+0029 ')'
    twine_text::GlyphDsc { bitmap_index: 41, adv_w: 128, box_w: 8, box_h: 5, ofs_x: 0, ofs_y: 2 }, // U+002A '*'
    twine_text::GlyphDsc { bitmap_index: 46, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 2 }, // U+002B '+'
    twine_text::GlyphDsc { bitmap_index: 50, adv_w: 128, box_w: 3, box_h: 3, ofs_x: 2, ofs_y: 0 }, // U+002C ','
    twine_text::GlyphDsc { bitmap_index: 52, adv_w: 128, box_w: 6, box_h: 1, ofs_x: 1, ofs_y: 4 }, // U+002D '-'
    twine_text::GlyphDsc { bitmap_index: 53, adv_w: 128, box_w: 2, box_h: 2, ofs_x: 3, ofs_y: 1 }, // U+002E '.'
    twine_text::GlyphDsc { bitmap_index: 54, adv_w: 128, box_w: 8, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+002F '/'
    twine_text::GlyphDsc { bitmap_index: 61, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0030 '0'
    twine_text::GlyphDsc { bitmap_index: 67, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0031 '1'
    twine_text::GlyphDsc { bitmap_index: 73, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0032 '2'
    twine_text::GlyphDsc { bitmap_index: 79, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0033 '3'
    twine_text::GlyphDsc { bitmap_index: 85, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0034 '4'
    twine_text::GlyphDsc { bitmap_index: 92, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0035 '5'
    twine_text::GlyphDsc { bitmap_index: 98, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0036 '6'
    twine_text::GlyphDsc { bitmap_index: 104, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0037 '7'
    twine_text::GlyphDsc { bitmap_index: 110, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0038 '8'
    twine_text::GlyphDsc { bitmap_index: 116, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0039 '9'
    twine_text::GlyphDsc { bitmap_index: 122, adv_w: 128, box_w: 2, box_h: 6, ofs_x: 3, ofs_y: 1 }, // U+003A ':'
    twine_text::GlyphDsc { bitmap_index: 124, adv_w: 128, box_w: 3, box_h: 7, ofs_x: 2, ofs_y: 0 }, // U+003B ';'
    twine_text::GlyphDsc { bitmap_index: 127, adv_w: 128, box_w: 5, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+003C '<'
    twine_text::GlyphDsc { bitmap_index: 132, adv_w: 128, box_w: 6, box_h: 3, ofs_x: 1, ofs_y: 3 }, // U+003D '='
    twine_text::GlyphDsc { bitmap_index: 135, adv_w: 128, box_w: 5, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+003E '>'
    twine_text::GlyphDsc { bitmap_index: 140, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+003F '?'
    twine_text::GlyphDsc { bitmap_index: 146, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0040 '@'
    twine_text::GlyphDsc { bitmap_index: 153, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0041 'A'
    twine_text::GlyphDsc { bitmap_index: 159, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0042 'B'
    twine_text::GlyphDsc { bitmap_index: 165, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0043 'C'
    twine_text::GlyphDsc { bitmap_index: 171, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0044 'D'
    twine_text::GlyphDsc { bitmap_index: 177, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0045 'E'
    twine_text::GlyphDsc { bitmap_index: 183, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0046 'F'
    twine_text::GlyphDsc { bitmap_index: 189, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0047 'G'
    twine_text::GlyphDsc { bitmap_index: 195, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0048 'H'
    twine_text::GlyphDsc { bitmap_index: 201, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0049 'I'
    twine_text::GlyphDsc { bitmap_index: 207, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+004A 'J'
    twine_text::GlyphDsc { bitmap_index: 213, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+004B 'K'
    twine_text::GlyphDsc { bitmap_index: 220, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+004C 'L'
    twine_text::GlyphDsc { bitmap_index: 226, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+004D 'M'
    twine_text::GlyphDsc { bitmap_index: 233, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+004E 'N'
    twine_text::GlyphDsc { bitmap_index: 240, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+004F 'O'
    twine_text::GlyphDsc { bitmap_index: 246, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0050 'P'
    twine_text::GlyphDsc { bitmap_index: 252, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0051 'Q'
    twine_text::GlyphDsc { bitmap_index: 258, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0052 'R'
    twine_text::GlyphDsc { bitmap_index: 264, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0053 'S'
    twine_text::GlyphDsc { bitmap_index: 270, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0054 'T'
    twine_text::GlyphDsc { bitmap_index: 276, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0055 'U'
    twine_text::GlyphDsc { bitmap_index: 282, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0056 'V'
    twine_text::GlyphDsc { bitmap_index: 288, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0057 'W'
    twine_text::GlyphDsc { bitmap_index: 295, adv_w: 128, box_w: 8, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0058 'X'
    twine_text::GlyphDsc { bitmap_index: 302, adv_w: 128, box_w: 8, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+0059 'Y'
    twine_text::GlyphDsc { bitmap_index: 309, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+005A 'Z'
    twine_text::GlyphDsc { bitmap_index: 315, adv_w: 128, box_w: 4, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+005B '['
    twine_text::GlyphDsc { bitmap_index: 319, adv_w: 128, box_w: 8, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+005C '\\'
    twine_text::GlyphDsc { bitmap_index: 326, adv_w: 128, box_w: 4, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+005D ']'
    twine_text::GlyphDsc { bitmap_index: 330, adv_w: 128, box_w: 7, box_h: 4, ofs_x: 0, ofs_y: 4 }, // U+005E '^'
    twine_text::GlyphDsc { bitmap_index: 334, adv_w: 128, box_w: 8, box_h: 1, ofs_x: 0, ofs_y: 0 }, // U+005F '_'
    twine_text::GlyphDsc { bitmap_index: 335, adv_w: 128, box_w: 4, box_h: 3, ofs_x: 3, ofs_y: 5 }, // U+0060 '`'
    twine_text::GlyphDsc { bitmap_index: 337, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0061 'a'
    twine_text::GlyphDsc { bitmap_index: 341, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0062 'b'
    twine_text::GlyphDsc { bitmap_index: 347, adv_w: 128, box_w: 5, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0063 'c'
    twine_text::GlyphDsc { bitmap_index: 351, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0064 'd'
    twine_text::GlyphDsc { bitmap_index: 357, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0065 'e'
    twine_text::GlyphDsc { bitmap_index: 361, adv_w: 128, box_w: 5, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0066 'f'
    twine_text::GlyphDsc { bitmap_index: 366, adv_w: 128, box_w: 6, box_h: 6, ofs_x: 1, ofs_y: 0 }, // U+0067 'g'
    twine_text::GlyphDsc { bitmap_index: 371, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0068 'h'
    twine_text::GlyphDsc { bitmap_index: 377, adv_w: 128, box_w: 5, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+0069 'i'
    twine_text::GlyphDsc { bitmap_index: 382, adv_w: 128, box_w: 5, box_h: 8, ofs_x: 1, ofs_y: 0 }, // U+006A 'j'
    twine_text::GlyphDsc { bitmap_index: 387, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+006B 'k'
    twine_text::GlyphDsc { bitmap_index: 393, adv_w: 128, box_w: 5, box_h: 7, ofs_x: 2, ofs_y: 1 }, // U+006C 'l'
    twine_text::GlyphDsc { bitmap_index: 398, adv_w: 128, box_w: 7, box_h: 5, ofs_x: 0, ofs_y: 1 }, // U+006D 'm'
    twine_text::GlyphDsc { bitmap_index: 403, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+006E 'n'
    twine_text::GlyphDsc { bitmap_index: 407, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+006F 'o'
    twine_text::GlyphDsc { bitmap_index: 411, adv_w: 128, box_w: 6, box_h: 6, ofs_x: 1, ofs_y: 0 }, // U+0070 'p'
    twine_text::GlyphDsc { bitmap_index: 416, adv_w: 128, box_w: 6, box_h: 6, ofs_x: 1, ofs_y: 0 }, // U+0071 'q'
    twine_text::GlyphDsc { bitmap_index: 421, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0072 'r'
    twine_text::GlyphDsc { bitmap_index: 425, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0073 's'
    twine_text::GlyphDsc { bitmap_index: 429, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+0074 't'
    twine_text::GlyphDsc { bitmap_index: 435, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0075 'u'
    twine_text::GlyphDsc { bitmap_index: 439, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+0076 'v'
    twine_text::GlyphDsc { bitmap_index: 443, adv_w: 128, box_w: 7, box_h: 5, ofs_x: 0, ofs_y: 1 }, // U+0077 'w'
    twine_text::GlyphDsc { bitmap_index: 448, adv_w: 128, box_w: 7, box_h: 5, ofs_x: 0, ofs_y: 1 }, // U+0078 'x'
    twine_text::GlyphDsc { bitmap_index: 453, adv_w: 128, box_w: 6, box_h: 6, ofs_x: 1, ofs_y: 0 }, // U+0079 'y'
    twine_text::GlyphDsc { bitmap_index: 458, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+007A 'z'
    twine_text::GlyphDsc { bitmap_index: 462, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+007B '{'
    twine_text::GlyphDsc { bitmap_index: 468, adv_w: 128, box_w: 2, box_h: 7, ofs_x: 3, ofs_y: 1 }, // U+007C '|'
    twine_text::GlyphDsc { bitmap_index: 470, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 1 }, // U+007D '}'
    twine_text::GlyphDsc { bitmap_index: 476, adv_w: 128, box_w: 7, box_h: 2, ofs_x: 0, ofs_y: 6 }, // U+007E '~'
    twine_text::GlyphDsc { bitmap_index: 478, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 1 }, // U+007F
];

#[rustfmt::skip]
static UNSCII_8_CMAPS: [twine_text::Cmap; 1] = [
    twine_text::Cmap { range_start: 0x20, range_length: 96, glyph_id_start: 1, unicode_list: &[], glyph_id_ofs_list: twine_text::GlyphIdOfs::None, kind: twine_text::CmapKind::Format0Tiny },
];

static UNSCII_8_DATA: twine_text::BitmapFont = twine_text::BitmapFont {
    bpp: 1,
    bitmap: &UNSCII_8_BITMAP,
    glyphs: &UNSCII_8_GLYPHS,
    cmaps: &UNSCII_8_CMAPS,
    kern: twine_text::Kern::None,
    kern_scale: 16,
    format: twine_text::BitmapFormat::Plain,
};

/// unscii-8.ttf at 8 px, 1 bpp, 96 glyphs (line height 8 px).
pub static UNSCII_8: twine_text::Font = twine_text::Font {
    line_height: 8,
    base_line: 0,
    underline_position: 0,
    underline_thickness: 1,
    provider: &UNSCII_8_DATA,
    fallback: None,
    subpx: twine_text::Subpx::None,
};
