// Generated by twine-cli 0.1.0: twine font --ttf assets/fonts/unscii-16.ttf --size 16 --bpp 1 --range 0x20-0x7F --no-kerning --name UNSCII_16 --out crates/twine-assets/src/fonts/unscii_16.rs
// Source: unscii-16.ttf SHA-256 0c889d6026f3bfe6cfa0e73833595678a548ed08dabeb1d71c5ad0fa9b309529
// 96 glyphs, line height 16 px, base line 0 px, 1 bpp, plain bitmaps, 0 kerning pairs.
// Do not edit: regenerate with the command above.

#[rustfmt::skip]
static UNSCII_16_BITMAP: [u8; 750] = [
    0xff, 0xff, 0x0f, 0xcf, 0x3c, 0xc0, 0x6c, 0xd9, 0xb7, 0xf6, 0xcd, 0x9b, 0x7f, 0x6c, 0xd9, 0xb0,
    0x30, 0xc7, 0xb3, 0xc1, 0x83, 0x06, 0x0f, 0x37, 0x8c, 0x30, 0x07, 0x8f, 0x36, 0x61, 0x83, 0x0c,
    0x18, 0x66, 0xcf, 0x1e, 0x00, 0x38, 0xd9, 0xb1, 0xc3, 0x0f, 0x77, 0xe6, 0xcd, 0x99, 0xd8, 0x6d,
    0xe0, 0x36, 0x6c, 0xcc, 0xcc, 0xcc, 0x66, 0x30, 0xc6, 0x63, 0x33, 0x33, 0x33, 0x66, 0xc0, 0x66,
    0x66, 0x3c, 0xff, 0x3c, 0x66, 0x66, 0x30, 0xc3, 0x3f, 0x30, 0xc3, 0x00, 0x73, 0x36, 0xc0, 0xfc,
    0xfc, 0x03, 0x03, 0x06, 0x06, 0x0c, 0x0c, 0x18, 0x18, 0x30, 0x30, 0x60, 0x60, 0xc0, 0xc0, 0x38,
    0xdb, 0x1e, 0x3c, 0xfa, 0xf9, 0xe3, 0xc6, 0xd8, 0xe0, 0x31, 0xcf, 0x0c, 0x30, 0xc3, 0x0c, 0x30,
    0xcf, 0xc0, 0x7b, 0x3c, 0xc3, 0x0c, 0x63, 0x18, 0xc3, 0x0f, 0xc0, 0x7b, 0x3c, 0xc3, 0x0c, 0xe0,
    0xc3, 0xcf, 0x37, 0x80, 0x0c, 0x38, 0xf3, 0x6c, 0xd9, 0xbf, 0x86, 0x0c, 0x18, 0x30, 0xff, 0x0c,
    0x30, 0xf8, 0x30, 0xc3, 0xcf, 0x37, 0x80, 0x39, 0x8c, 0x30, 0xfb, 0x3c, 0xf3, 0xcf, 0x37, 0x80,
    0xfc, 0x30, 0xc3, 0x18, 0x63, 0x0c, 0x30, 0xc3, 0x00, 0x7b, 0x3c, 0xf3, 0xed, 0xed, 0xf3, 0xcf,
    0x37, 0x80, 0x7b, 0x3c, 0xf3, 0xcd, 0xf0, 0xc3, 0x0c, 0x67, 0x00, 0xfc, 0x03, 0xf0, 0x33, 0x30,
    0x00, 0x07, 0x33, 0x6c, 0x0c, 0x63, 0x18, 0xc1, 0x83, 0x06, 0x0c, 0xfc, 0x00, 0x00, 0xfc, 0xc1,
    0x83, 0x06, 0x0c, 0x63, 0x18, 0xc0, 0x7b, 0x3c, 0xc3, 0x18, 0xc3, 0x0c, 0x00, 0x03, 0x0c, 0x7d,
    0x8f, 0x1e, 0x3d, 0xfb, 0xf7, 0xee, 0xc1, 0x81, 0xf0, 0x31, 0xec, 0xf3, 0xcf, 0xfc, 0xf3, 0xcf,
    0x3c, 0xc0, 0xfb, 0x3c, 0xf3, 0xdb, 0xcd, 0xb3, 0xcf, 0x3f, 0x80, 0x7b, 0x3c, 0xf0, 0xc3, 0x0c,
    0x30, 0xcf, 0x37, 0x80, 0xf3, 0x6c, 0xf3, 0xcf, 0x3c, 0xf3, 0xcf, 0x6f, 0x00, 0xff, 0x0c, 0x30,
    0xc3, 0xec, 0x30, 0xc3, 0x0f, 0xc0, 0xff, 0x0c, 0x30, 0xfb, 0x0c, 0x30, 0xc3, 0x0c, 0x00, 0x7b,
    0x3c, 0xf0, 0xc3, 0x7c, 0xf3, 0xcf, 0x37, 0xc0, 0xcf, 0x3c, 0xf3, 0xcf, 0xfc, 0xf3, 0xcf, 0x3c,
    0xc0, 0xfc, 0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0x30, 0xcf, 0xc0, 0x0c, 0x30, 0xc3, 0x0c, 0x30, 0xc3,
    0xcf, 0x37, 0x80, 0xc7, 0x8f, 0x36, 0x6d, 0x9e, 0x36, 0x66, 0xcd, 0x8f, 0x18, 0xc3, 0x0c, 0x30,
    0xc3, 0x0c, 0x30, 0xc3, 0x0f, 0xc0, 0xc7, 0xdf, 0xbf, 0xfd, 0x7a, 0xf1, 0xe3, 0xc7, 0x8f, 0x18,
    0xc7, 0x8f, 0x9f, 0x3f, 0x7f, 0xf7, 0xe7, 0xcf, 0x8f, 0x18, 0x7b, 0x3c, 0xf3, 0xcf, 0x3c, 0xf3,
    0xcf, 0x37, 0x80, 0xfb, 0x3c, 0xf3, 0xcf, 0xec, 0x30, 0xc3, 0x0c, 0x00, 0x7b, 0x3c, 0xf3, 0xcf,
    0x3c, 0xf3, 0xcf, 0x37, 0x86, 0x0c, 0xfb, 0x3c, 0xf3, 0xcf, 0xed, 0xb3, 0xcf, 0x3c, 0xc0, 0x7b,
    0x3c, 0xf0, 0x60, 0xc1, 0x83, 0xcf, 0x37, 0x80, 0xfc, 0xc3, 0x0c, 0x30, 0xc3, 0x0c, 0x30, 0xc3,
    0x00, 0xcf, 0x3c, 0xf3, 0xcf, 0x3c, 0xf3, 0xcf, 0x37, 0x80, 0xcf, 0x3c, 0xf3, 0xcf, 0x3c, 0xde,
    0x78, 0xc3, 0x00, 0xc7, 0x8f, 0x1e, 0x3c, 0x7a, 0xf5, 0xff, 0xef, 0xdf, 0x18, 0xc3, 0xc3, 0x66,
    0x3c, 0x18, 0x18, 0x18, 0x3c, 0x66, 0xc3, 0xc3, 0xc3, 0xc3, 0x66, 0x66, 0x3c, 0x18, 0x18, 0x18,
    0x18, 0x18, 0x18, 0xfc, 0x30, 0xc6, 0x18, 0xc6, 0x18, 0xc3, 0x0f, 0xc0, 0xfc, 0xcc, 0xcc, 0xcc,
    0xcc, 0xcc, 0xf0, 0xc0, 0xc0, 0x60, 0x60, 0x30, 0x30, 0x18, 0x18, 0x0c, 0x0c, 0x06, 0x06, 0x03,
    0x03, 0xf3, 0x33, 0x33, 0x33, 0x33, 0x33, 0xf0, 0x10, 0x71, 0xb3, 0x6c, 0x78, 0xc0, 0xff, 0xcc,
    0x63, 0x78, 0x37, 0xf3, 0xcf, 0x37, 0xc0, 0xc3, 0x0c, 0x30, 0xfb, 0x3c, 0xf3, 0xcf, 0x3f, 0x80,
    0x7b, 0x3c, 0x30, 0xc3, 0x37, 0x80, 0x0c, 0x30, 0xc3, 0x7f, 0x3c, 0xf3, 0xcf, 0x37, 0xc0, 0x7b,
    0x3c, 0xff, 0xc3, 0x07, 0x80, 0x3d, 0x86, 0x18, 0xfd, 0x86, 0x18, 0x61, 0x86, 0x00, 0x7f, 0x3c,
    0xf3, 0xcf, 0x37, 0xc3, 0x0f, 0xe0, 0xc3, 0x0c, 0x30, 0xfb, 0x3c, 0xf3, 0xcf, 0x3c, 0xc0, 0x30,
    0xc0, 0x00, 0xf0, 0xc3, 0x0c, 0x30, 0xc3, 0xc0, 0x18, 0xc0, 0x01, 0x8c, 0x63, 0x18, 0xc6, 0x31,
    0xf8, 0xc3, 0x0c, 0x30, 0xcf, 0x3d, 0xbc, 0xdb, 0x3c, 0xc0, 0xf0, 0xc3, 0x0c, 0x30, 0xc3, 0x0c,
    0x30, 0xc3, 0xc0, 0xcd, 0xff, 0x5e, 0xbd, 0x7a, 0xf1, 0x80, 0xfb, 0x3c, 0xf3, 0xcf, 0x3c, 0xc0,
    0x7b, 0x3c, 0xf3, 0xcf, 0x37, 0x80, 0xfb, 0x3c, 0xf3, 0xcf, 0x3f, 0xb0, 0xc3, 0x00, 0x7f, 0x3c,
    0xf3, 0xcf, 0x37, 0xc3, 0x0c, 0x30, 0xfb, 0x3c, 0xf0, 0xc3, 0x0c, 0x00, 0x7f, 0x0c, 0x1e, 0x0c,
    0x3f, 0x80, 0x61, 0x86, 0x3f, 0x61, 0x86, 0x18, 0x60, 0xf0, 0xcf, 0x3c, 0xf3, 0xcf, 0x37, 0xc0,
    0xcf, 0x3c, 0xf3, 0xcd, 0xe3, 0x00, 0xc7, 0x8f, 0x5e, 0xbd, 0x6f, 0x9b, 0x00, 0xc7, 0x8d, 0xb1,
    0xc6, 0xd8, 0xf1, 0x80, 0xcf, 0x3c, 0xf3, 0xcf, 0x37, 0xc3, 0x0d, 0xe0, 0xfc, 0x31, 0x8c, 0x63,
    0x0f, 0xc0, 0x0e, 0x30, 0x60, 0xc1, 0x83, 0x3c, 0x0c, 0x18, 0x30, 0x60, 0xc0, 0xe0, 0xff, 0xff,
    0xff, 0xf0, 0xe0, 0x60, 0xc1, 0x83, 0x06, 0x07, 0x98, 0x30, 0x60, 0xc1, 0x8e, 0x00, 0x73, 0xae,
    0x70, 0xc1, 0x82, 0x85, 0x0a, 0xf5, 0xe9, 0x52, 0xc5, 0x88, 0x10, 0x20, 0x40, 0x80,
];

#[rustfmt::skip]
static UNSCII_16_GLYPHS: [twine_text::GlyphDsc; 97] = [
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 0, box_w: 0, box_h: 0, ofs_x: 0, ofs_y: 0 }, // reserved
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 128, box_w: 0, box_h: 0, ofs_x: 0, ofs_y: 0 }, // U+0020 ' '
    twine_text::GlyphDsc { bitmap_index: 0, adv_w: 128, box_w: 2, box_h: 12, ofs_x: 3, ofs_y: 3 }, // U+0021 '!'
    twine_text::GlyphDsc { bitmap_index: 3, adv_w: 128, box_w: 6, box_h: 3, ofs_x: 1, ofs_y: 12 }, // U+0022 '"'
    twine_text::GlyphDsc { bitmap_index: 6, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0023 '#'
    twine_text::GlyphDsc { bitmap_index: 16, adv_w: 128, box_w: 6, box_h: 13, ofs_x: 1, ofs_y: 2 }, // U+0024 '$'
    twine_text::GlyphDsc { bitmap_index: 26, adv_w: 128, box_w: 7, box_h: 12, ofs_x: 0, ofs_y: 2 }, // U+0025 '%'
    twine_text::GlyphDsc { bitmap_index: 37, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0026 '&'
    twine_text::GlyphDsc { bitmap_index: 47, adv_w: 128, box_w: 3, box_h: 4, ofs_x: 2, ofs_y: 11 }, // U+0027 '\''
    twine_text::GlyphDsc { bitmap_index: 49, adv_w: 128, box_w: 4, box_h: 13, ofs_x: 2, ofs_y: 2 }, // U+0028 '('
    twine_text::GlyphDsc { bitmap_index: 56, adv_w: 128, box_w: 4, box_h: 13, ofs_x: 2, ofs_y: 2 }, // U+0029 ')'
    twine_text::GlyphDsc { bitmap_index: 63, adv_w: 128, box_w: 8, box_h: 7, ofs_x: 0, ofs_y: 5 }, // U+002A '*'
    twine_text::GlyphDsc { bitmap_index: 70, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 5 }, // U+002B '+'
    twine_text::GlyphDsc { bitmap_index: 76, adv_w: 128, box_w: 4, box_h: 5, ofs_x: 1, ofs_y: 1 }, // U+002C ','
    twine_text::GlyphDsc { bitmap_index: 79, adv_w: 128, box_w: 6, box_h: 1, ofs_x: 1, ofs_y: 8 }, // U+002D '-'
    twine_text::GlyphDsc { bitmap_index: 80, adv_w: 128, box_w: 2, box_h: 3, ofs_x: 3, ofs_y: 3 }, // U+002E '.'
    twine_text::GlyphDsc { bitmap_index: 81, adv_w: 128, box_w: 8, box_h: 14, ofs_x: 0, ofs_y: 2 }, // U+002F '/'
    twine_text::GlyphDsc { bitmap_index: 95, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0030 '0'
    twine_text::GlyphDsc { bitmap_index: 105, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0031 '1'
    twine_text::GlyphDsc { bitmap_index: 114, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0032 '2'
    twine_text::GlyphDsc { bitmap_index: 123, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0033 '3'
    twine_text::GlyphDsc { bitmap_index: 132, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0034 '4'
    twine_text::GlyphDsc { bitmap_index: 142, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0035 '5'
    twine_text::GlyphDsc { bitmap_index: 151, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0036 '6'
    twine_text::GlyphDsc { bitmap_index: 160, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0037 '7'
    twine_text::GlyphDsc { bitmap_index: 169, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0038 '8'
    twine_text::GlyphDsc { bitmap_index: 178, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0039 '9'
    twine_text::GlyphDsc { bitmap_index: 187, adv_w: 128, box_w: 2, box_h: 10, ofs_x: 3, ofs_y: 3 }, // U+003A ':'
    twine_text::GlyphDsc { bitmap_index: 190, adv_w: 128, box_w: 4, box_h: 12, ofs_x: 1, ofs_y: 1 }, // U+003B ';'
    twine_text::GlyphDsc { bitmap_index: 196, adv_w: 128, box_w: 6, box_h: 9, ofs_x: 1, ofs_y: 4 }, // U+003C '<'
    twine_text::GlyphDsc { bitmap_index: 203, adv_w: 128, box_w: 6, box_h: 5, ofs_x: 1, ofs_y: 6 }, // U+003D '='
    twine_text::GlyphDsc { bitmap_index: 207, adv_w: 128, box_w: 6, box_h: 9, ofs_x: 1, ofs_y: 4 }, // U+003E '>'
    twine_text::GlyphDsc { bitmap_index: 214, adv_w: 128, box_w: 6, box_h: 12, ofs_x: 1, ofs_y: 3 }, // U+003F '?'
    twine_text::GlyphDsc { bitmap_index: 223, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0040 '@'
    twine_text::GlyphDsc { bitmap_index: 233, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0041 'A'
    twine_text::GlyphDsc { bitmap_index: 242, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0042 'B'
    twine_text::GlyphDsc { bitmap_index: 251, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0043 'C'
    twine_text::GlyphDsc { bitmap_index: 260, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0044 'D'
    twine_text::GlyphDsc { bitmap_index: 269, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0045 'E'
    twine_text::GlyphDsc { bitmap_index: 278, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0046 'F'
    twine_text::GlyphDsc { bitmap_index: 287, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0047 'G'
    twine_text::GlyphDsc { bitmap_index: 296, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0048 'H'
    twine_text::GlyphDsc { bitmap_index: 305, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0049 'I'
    twine_text::GlyphDsc { bitmap_index: 314, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+004A 'J'
    twine_text::GlyphDsc { bitmap_index: 323, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+004B 'K'
    twine_text::GlyphDsc { bitmap_index: 333, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+004C 'L'
    twine_text::GlyphDsc { bitmap_index: 342, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+004D 'M'
    twine_text::GlyphDsc { bitmap_index: 352, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+004E 'N'
    twine_text::GlyphDsc { bitmap_index: 362, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+004F 'O'
    twine_text::GlyphDsc { bitmap_index: 371, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0050 'P'
    twine_text::GlyphDsc { bitmap_index: 380, adv_w: 128, box_w: 6, box_h: 13, ofs_x: 1, ofs_y: 1 }, // U+0051 'Q'
    twine_text::GlyphDsc { bitmap_index: 390, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0052 'R'
    twine_text::GlyphDsc { bitmap_index: 399, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0053 'S'
    twine_text::GlyphDsc { bitmap_index: 408, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0054 'T'
    twine_text::GlyphDsc { bitmap_index: 417, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0055 'U'
    twine_text::GlyphDsc { bitmap_index: 426, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0056 'V'
    twine_text::GlyphDsc { bitmap_index: 435, adv_w: 128, box_w: 7, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0057 'W'
    twine_text::GlyphDsc { bitmap_index: 445, adv_w: 128, box_w: 8, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0058 'X'
    twine_text::GlyphDsc { bitmap_index: 456, adv_w: 128, box_w: 8, box_h: 11, ofs_x: 0, ofs_y: 3 }, // U+0059 'Y'
    twine_text::GlyphDsc { bitmap_index: 467, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+005A 'Z'
    twine_text::GlyphDsc { bitmap_index: 476, adv_w: 128, box_w: 4, box_h: 13, ofs_x: 2, ofs_y: 2 }, // U+005B '['
    twine_text::GlyphDsc { bitmap_index: 483, adv_w: 128, box_w: 8, box_h: 14, ofs_x: 0, ofs_y: 2 }, // U+005C '\\'
    twine_text::GlyphDsc { bitmap_index: 497, adv_w: 128, box_w: 4, box_h: 13, ofs_x: 2, ofs_y: 2 }, // U+005D ']'
    twine_text::GlyphDsc { bitmap_index: 504, adv_w: 128, box_w: 7, box_h: 6, ofs_x: 0, ofs_y: 9 }, // U+005E '^'
    twine_text::GlyphDsc { bitmap_index: 510, adv_w: 128, box_w: 8, box_h: 1, ofs_x: 0, ofs_y: 0 }, // U+005F '_'
    twine_text::GlyphDsc { bitmap_index: 511, adv_w: 128, box_w: 4, box_h: 4, ofs_x: 3, ofs_y: 11 }, // U+0060 '`'
    twine_text::GlyphDsc { bitmap_index: 513, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0061 'a'
    twine_text::GlyphDsc { bitmap_index: 519, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0062 'b'
    twine_text::GlyphDsc { bitmap_index: 528, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0063 'c'
    twine_text::GlyphDsc { bitmap_index: 534, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0064 'd'
    twine_text::GlyphDsc { bitmap_index: 543, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0065 'e'
    twine_text::GlyphDsc { bitmap_index: 549, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0066 'f'
    twine_text::GlyphDsc { bitmap_index: 558, adv_w: 128, box_w: 6, box_h: 10, ofs_x: 1, ofs_y: 0 }, // U+0067 'g'
    twine_text::GlyphDsc { bitmap_index: 566, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0068 'h'
    twine_text::GlyphDsc { bitmap_index: 575, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+0069 'i'
    twine_text::GlyphDsc { bitmap_index: 584, adv_w: 128, box_w: 5, box_h: 14, ofs_x: 1, ofs_y: 0 }, // U+006A 'j'
    twine_text::GlyphDsc { bitmap_index: 593, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+006B 'k'
    twine_text::GlyphDsc { bitmap_index: 602, adv_w: 128, box_w: 6, box_h: 11, ofs_x: 1, ofs_y: 3 }, // U+006C 'l'
    twine_text::GlyphDsc { bitmap_index: 611, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 3 }, // U+006D 'm'
    twine_text::GlyphDsc { bitmap_index: 618, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+006E 'n'
    twine_text::GlyphDsc { bitmap_index: 624, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+006F 'o'
    twine_text::GlyphDsc { bitmap_index: 630, adv_w: 128, box_w: 6, box_h: 10, ofs_x: 1, ofs_y: 0 }, // U+0070 'p'
    twine_text::GlyphDsc { bitmap_index: 638, adv_w: 128, box_w: 6, box_h: 10, ofs_x: 1, ofs_y: 0 }, // U+0071 'q'
    twine_text::GlyphDsc { bitmap_index: 646, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0072 'r'
    twine_text::GlyphDsc { bitmap_index: 652, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0073 's'
    twine_text::GlyphDsc { bitmap_index: 658, adv_w: 128, box_w: 6, box_h: 10, ofs_x: 1, ofs_y: 3 }, // U+0074 't'
    twine_text::GlyphDsc { bitmap_index: 666, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0075 'u'
    twine_text::GlyphDsc { bitmap_index: 672, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+0076 'v'
    twine_text::GlyphDsc { bitmap_index: 678, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 3 }, // U+0077 'w'
    twine_text::GlyphDsc { bitmap_index: 685, adv_w: 128, box_w: 7, box_h: 7, ofs_x: 0, ofs_y: 3 }, // U+0078 'x'
    twine_text::GlyphDsc { bitmap_index: 692, adv_w: 128, box_w: 6, box_h: 10, ofs_x: 1, ofs_y: 0 }, // U+0079 'y'
    twine_text::GlyphDsc { bitmap_index: 700, adv_w: 128, box_w: 6, box_h: 7, ofs_x: 1, ofs_y: 3 }, // U+007A 'z'
    twine_text::GlyphDsc { bitmap_index: 706, adv_w: 128, box_w: 7, box_h: 13, ofs_x: 0, ofs_y: 2 }, // U+007B '{'
    twine_text::GlyphDsc { bitmap_index: 718, adv_w: 128, box_w: 2, box_h: 14, ofs_x: 3, ofs_y: 2 }, // U+007C '|'
    twine_text::GlyphDsc { bitmap_index: 722, adv_w: 128, box_w: 7, box_h: 13, ofs_x: 0, ofs_y: 2 }, // U+007D '}'
    twine_text::GlyphDsc { bitmap_index: 734, adv_w: 128, box_w: 7, box_h: 3, ofs_x: 0, ofs_y: 12 }, // U+007E '~'
    twine_text::GlyphDsc { bitmap_index: 737, adv_w: 128, box_w: 7, box_h: 14, ofs_x: 0, ofs_y: 2 }, // U+007F
];

#[rustfmt::skip]
static UNSCII_16_CMAPS: [twine_text::Cmap; 1] = [
    twine_text::Cmap { range_start: 0x20, range_length: 96, glyph_id_start: 1, unicode_list: &[], glyph_id_ofs_list: twine_text::GlyphIdOfs::None, kind: twine_text::CmapKind::Format0Tiny },
];

static UNSCII_16_DATA: twine_text::BitmapFont = twine_text::BitmapFont {
    bpp: 1,
    bitmap: &UNSCII_16_BITMAP,
    glyphs: &UNSCII_16_GLYPHS,
    cmaps: &UNSCII_16_CMAPS,
    kern: twine_text::Kern::None,
    kern_scale: 16,
    format: twine_text::BitmapFormat::Plain,
};

/// unscii-16.ttf at 16 px, 1 bpp, 96 glyphs (line height 16 px).
pub static UNSCII_16: twine_text::Font = twine_text::Font {
    line_height: 16,
    base_line: 0,
    underline_position: 0,
    underline_thickness: 1,
    provider: &UNSCII_16_DATA,
    fallback: None,
    subpx: twine_text::Subpx::None,
};
