//! # twine-assets
//!
//! Built-in fonts of the Twine GUI library as `static` [`Font`](twine_text::Font)s, one cargo
//! feature per font (`default = ["montserrat-14"]`, `all-fonts` enables all of them). Fonts
//! that are not enabled cost nothing.
//!
//! - **Montserrat Medium** 8–48 px (even sizes), 4 bpp: ASCII, `°`, `•` and every
//!   [`twine_text::symbols`] icon (Font Awesome Free). Up to 16 px the bitmaps are stored
//!   plain (fastest to draw), larger sizes are RLE-compressed (smaller; decoded glyphs are
//!   kept in the glyph cache). Kerning from the font's `GPOS` table is included.
//! - **Montserrat Medium 14 px subpixel** (`montserrat-14-subpx`): horizontal RGB subpixel
//!   glyphs for LCD panels with a known subpixel order.
//! - **unscii** 8 and 16 px, 1 bpp, ASCII: pixel-exact bitmap fonts.
//!
//! The files in `src/fonts/` are generated by `cargo xtask fonts` from
//! `assets/fonts/fonts.toml` (sources, licenses and SHA-256 hashes of the TTF files are in
//! `assets/fonts/SOURCES.md`); never edit them by hand.
//!
//! ## Sizes
//!
//! Static data per font (bitmaps, glyph descriptors, cmaps, kerning; descriptor sizes as on a
//! 64-bit host):
//!
//! | feature | glyphs | line height | flash bytes |
//! |---|---:|---:|---:|
//! | `montserrat-8` | 157 | 11 | 13785 |
//! | `montserrat-10` | 157 | 13 | 15486 |
//! | `montserrat-12` | 157 | 16 | 17377 |
//! | `montserrat-14` | 157 | 18 | 19581 |
//! | `montserrat-16` | 157 | 21 | 21871 |
//! | `montserrat-18` | 157 | 23 | 20600 |
//! | `montserrat-20` | 157 | 26 | 21965 |
//! | `montserrat-22` | 157 | 28 | 23746 |
//! | `montserrat-24` | 157 | 31 | 24986 |
//! | `montserrat-26` | 157 | 33 | 27200 |
//! | `montserrat-28` | 157 | 36 | 28917 |
//! | `montserrat-30` | 157 | 38 | 30697 |
//! | `montserrat-32` | 157 | 40 | 32115 |
//! | `montserrat-34` | 157 | 42 | 34820 |
//! | `montserrat-36` | 157 | 45 | 36610 |
//! | `montserrat-38` | 157 | 47 | 38471 |
//! | `montserrat-40` | 157 | 50 | 39955 |
//! | `montserrat-42` | 157 | 52 | 42323 |
//! | `montserrat-44` | 157 | 55 | 44050 |
//! | `montserrat-46` | 157 | 57 | 46113 |
//! | `montserrat-48` | 157 | 60 | 46977 |
//! | `montserrat-14-subpx` | 157 | 18 | 40998 |
//! | `unscii-8` | 96 | 8 | 1849 |
//! | `unscii-16` | 96 | 16 | 2114 |
//!
//! ## Example
//!
//! ```
//! use twine_assets::fonts::MONTSERRAT_14;
//! use twine_text::TextLayout;
//!
//! let size = TextLayout::new("Hello", &MONTSERRAT_14).measure();
//! assert_eq!(size.h, i32::from(MONTSERRAT_14.line_height));
//! assert!(size.w > 20);
//! ```
#![no_std]
#![forbid(unsafe_code)]

/// The built-in fonts (each behind its cargo feature).
pub mod fonts {
    #[cfg(feature = "montserrat-8")]
    mod montserrat_8;
    #[cfg(feature = "montserrat-8")]
    pub use montserrat_8::MONTSERRAT_8;
    #[cfg(feature = "montserrat-10")]
    mod montserrat_10;
    #[cfg(feature = "montserrat-10")]
    pub use montserrat_10::MONTSERRAT_10;
    #[cfg(feature = "montserrat-12")]
    mod montserrat_12;
    #[cfg(feature = "montserrat-12")]
    pub use montserrat_12::MONTSERRAT_12;
    #[cfg(feature = "montserrat-14")]
    mod montserrat_14;
    #[cfg(feature = "montserrat-14")]
    pub use montserrat_14::MONTSERRAT_14;
    #[cfg(feature = "montserrat-16")]
    mod montserrat_16;
    #[cfg(feature = "montserrat-16")]
    pub use montserrat_16::MONTSERRAT_16;
    #[cfg(feature = "montserrat-18")]
    mod montserrat_18;
    #[cfg(feature = "montserrat-18")]
    pub use montserrat_18::MONTSERRAT_18;
    #[cfg(feature = "montserrat-20")]
    mod montserrat_20;
    #[cfg(feature = "montserrat-20")]
    pub use montserrat_20::MONTSERRAT_20;
    #[cfg(feature = "montserrat-22")]
    mod montserrat_22;
    #[cfg(feature = "montserrat-22")]
    pub use montserrat_22::MONTSERRAT_22;
    #[cfg(feature = "montserrat-24")]
    mod montserrat_24;
    #[cfg(feature = "montserrat-24")]
    pub use montserrat_24::MONTSERRAT_24;
    #[cfg(feature = "montserrat-26")]
    mod montserrat_26;
    #[cfg(feature = "montserrat-26")]
    pub use montserrat_26::MONTSERRAT_26;
    #[cfg(feature = "montserrat-28")]
    mod montserrat_28;
    #[cfg(feature = "montserrat-28")]
    pub use montserrat_28::MONTSERRAT_28;
    #[cfg(feature = "montserrat-30")]
    mod montserrat_30;
    #[cfg(feature = "montserrat-30")]
    pub use montserrat_30::MONTSERRAT_30;
    #[cfg(feature = "montserrat-32")]
    mod montserrat_32;
    #[cfg(feature = "montserrat-32")]
    pub use montserrat_32::MONTSERRAT_32;
    #[cfg(feature = "montserrat-34")]
    mod montserrat_34;
    #[cfg(feature = "montserrat-34")]
    pub use montserrat_34::MONTSERRAT_34;
    #[cfg(feature = "montserrat-36")]
    mod montserrat_36;
    #[cfg(feature = "montserrat-36")]
    pub use montserrat_36::MONTSERRAT_36;
    #[cfg(feature = "montserrat-38")]
    mod montserrat_38;
    #[cfg(feature = "montserrat-38")]
    pub use montserrat_38::MONTSERRAT_38;
    #[cfg(feature = "montserrat-40")]
    mod montserrat_40;
    #[cfg(feature = "montserrat-40")]
    pub use montserrat_40::MONTSERRAT_40;
    #[cfg(feature = "montserrat-42")]
    mod montserrat_42;
    #[cfg(feature = "montserrat-42")]
    pub use montserrat_42::MONTSERRAT_42;
    #[cfg(feature = "montserrat-44")]
    mod montserrat_44;
    #[cfg(feature = "montserrat-44")]
    pub use montserrat_44::MONTSERRAT_44;
    #[cfg(feature = "montserrat-46")]
    mod montserrat_46;
    #[cfg(feature = "montserrat-46")]
    pub use montserrat_46::MONTSERRAT_46;
    #[cfg(feature = "montserrat-48")]
    mod montserrat_48;
    #[cfg(feature = "montserrat-48")]
    pub use montserrat_48::MONTSERRAT_48;
    #[cfg(feature = "montserrat-14-subpx")]
    mod montserrat_14_subpx;
    #[cfg(feature = "montserrat-14-subpx")]
    pub use montserrat_14_subpx::MONTSERRAT_14_SUBPX;
    #[cfg(feature = "unscii-8")]
    mod unscii_8;
    #[cfg(feature = "unscii-8")]
    pub use unscii_8::UNSCII_8;
    #[cfg(feature = "unscii-16")]
    mod unscii_16;
    #[cfg(feature = "unscii-16")]
    pub use unscii_16::UNSCII_16;
}
