[package]
name = "twine-drivers"
description = "Display, touch and input drivers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
twine-core = { path = "../twine-core" }
twine-hal = { path = "../twine-hal" }
