//! Font generator tests (need `assets/fonts/Montserrat-Medium.ttf`).

use std::path::{Path, PathBuf};

use clap::Parser;
use proptest::prelude::*;
use twine_cli::font::{FontArgs, FontOptions, SubpxArg, Symbols, generate, merge_ranges, quantize};
use twine_text::encode::{load_generated_for_test, rle_decode, rle_encode};
use twine_text::{GlyphCache, Subpx};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn opts(size: u16, compress: bool) -> FontOptions {
    FontOptions {
        ttf: "assets/fonts/Montserrat-Medium.ttf".into(),
        size,
        bpp: 4,
        ranges: vec!["0x20-0x7E".into(), "0xB0".into()],
        chars_files: Vec::new(),
        symbols: Symbols::None,
        symbols_ttf: Vec::new(),
        compress,
        prefilter: true,
        kerning: true,
        subpx: SubpxArg::None,
        name: "TEST_FONT".into(),
        out: "target/test_font.rs".into(),
    }
}

#[test]
fn generate_is_deterministic() {
    let a = generate(&opts(14, true), &root()).unwrap();
    let b = generate(&opts(14, true), &root()).unwrap();
    assert_eq!(a.source, b.source);
    assert!(a.source.starts_with("// Generated by twine-cli "));
    assert!(
        a.source
            .contains("twine font --ttf assets/fonts/Montserrat-Medium.ttf --size 14 --bpp 4")
    );
    assert!(
        a.source
            .contains("SHA-256 c888ea70fdceef0d05752266472a940aeb86692a7bdf8f2211380587418ca223")
    );
}

fn check_roundtrip(values: &[u8], bpp: u8) {
    let enc = rle_encode(values, bpp);
    assert_eq!(rle_decode(&enc, bpp, values.len()), values, "bpp {bpp}");
}

#[test]
fn rle_roundtrip_runs_of_exactly_11_12_63_64_200() {
    for bpp in [1u8, 2, 4, 8] {
        let max = ((1u16 << bpp) - 1) as u8;
        for run in [1usize, 2, 3, 11, 12, 13, 62, 63, 64, 65, 74, 75, 76, 200] {
            let mut v = vec![0u8; 3];
            v.extend(std::iter::repeat_n(max, run));
            check_roundtrip(&v, bpp);
            v.push(1);
            check_roundtrip(&v, bpp);
            v.extend(std::iter::repeat_n(0, run));
            check_roundtrip(&v, bpp);
        }
    }
}

fn biased_values() -> impl Strategy<Value = (u8, Vec<u8>)> {
    prop::sample::select(vec![1u8, 2, 4, 8]).prop_flat_map(|bpp| {
        let max = ((1u16 << bpp) - 1) as u8;
        // Runs of random length (often long) of random values.
        let runs = prop::collection::vec((0..=max, prop_oneof![1usize..4, 1usize..80, 60usize..140]), 1..40);
        runs.prop_map(move |rs| {
            let mut v: Vec<u8> = rs
                .into_iter()
                .flat_map(|(x, n)| std::iter::repeat_n(x, n))
                .collect();
            v.truncate(2000);
            (bpp, v)
        })
    })
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(
        std::env::var("PROPTEST_CASES").ok().and_then(|s| s.parse().ok()).unwrap_or(1000)))]
    #[test]
    fn rle_roundtrip_random((bpp, values) in biased_values()) {
        prop_assert_eq!(rle_decode(&rle_encode(&values, bpp), bpp, values.len()), values);
    }
}

#[test]
fn generated_font_matches_fontdue_coverage() {
    for compress in [false, true] {
        for size in [14u16, 28] {
            let g = generate(&opts(size, compress), &root()).unwrap();
            let font = load_generated_for_test(&g.data);
            let bytes = std::fs::read(root().join("assets/fonts/Montserrat-Medium.ttf")).unwrap();
            let settings = fontdue::FontSettings {
                scale: f32::from(size),
                ..fontdue::FontSettings::default()
            };
            let fd = fontdue::Font::from_bytes(bytes.as_slice(), settings).unwrap();
            let mut cache = GlyphCache::new(if compress { 2048 } else { 0 });
            for c in "AVWagjQ@%&#0189,.;|~}".chars().take(20) {
                let (_, info) = font.glyph(c, None).unwrap();
                // Reference: fontdue coverage, trimmed and quantized.
                let (cov, _) = twine_cli::font::raster(&fd, c, f32::from(size));
                let cov = cov.trim(1, 1);
                assert_eq!(
                    (i32::from(info.box_w), i32::from(info.box_h)),
                    (cov.w, cov.h),
                    "{c:?} box"
                );
                assert_eq!(
                    (i32::from(info.ofs_x), i32::from(info.ofs_y)),
                    (cov.x0, cov.y0),
                    "{c:?} offset"
                );
                let mut out = vec![0u8; cov.data.len()];
                for _pass in 0..2 {
                    assert!(font.provider.render_a8(&info, &mut out, &mut cache));
                    let expected: Vec<u8> = cov.data.iter().map(|&v| quantize(v, 4) * 17).collect();
                    assert_eq!(out, expected, "{c:?} size {size} compress {compress}");
                }
                assert_eq!(font.subpx, Subpx::None);
            }
            if compress {
                assert!(cache.stats().hits > 0, "second pass hits the cache");
            }
        }
    }
}

#[test]
fn kerning_is_read_from_gpos() {
    let g = generate(&opts(20, false), &root()).unwrap();
    let font = load_generated_for_test(&g.data);
    let plain = font.glyph('A', None).unwrap().1.adv_w;
    let kerned = font.glyph('A', Some('V')).unwrap().1.adv_w;
    assert!(kerned < plain, "A→V is kerned tighter ({kerned} vs {plain})");
}

#[test]
fn ranges_merge_and_sort() {
    let r = merge_ranges(&["0x43-0x44".into(), "65".into(), "chars:DB°".into(), "0x41".into()]).unwrap();
    assert_eq!(r, vec!['A', 'B', 'C', 'D', '°']);
}

#[test]
fn cli_rejects_invalid_bpp() {
    #[derive(Parser)]
    struct Wrap {
        #[command(flatten)]
        args: FontArgs,
    }
    let base = [
        "twine", "--ttf", "a.ttf", "--size", "14", "--name", "X", "--out", "x.rs",
    ];
    for ok in ["1", "2", "4", "8"] {
        assert!(Wrap::try_parse_from(base.iter().copied().chain(["--bpp", ok])).is_ok());
    }
    for bad in ["3", "0", "16", "x"] {
        let e = Wrap::try_parse_from(base.iter().copied().chain(["--bpp", bad]))
            .err()
            .unwrap();
        assert!(e.to_string().contains("bpp"), "{e}");
    }
    let mut o = opts(14, false);
    o.bpp = 3;
    assert!(generate(&o, &root()).is_err());
}

#[test]
fn symbols_are_merged_and_centered() {
    let mut o = opts(14, false);
    o.symbols = Symbols::Fa;
    let g = generate(&o, &root()).unwrap();
    let font = load_generated_for_test(&g.data);
    for &c in twine_text::symbols::ALL {
        let (_, info) = font.glyph(c, None).unwrap();
        assert!(info.box_h > 0, "{c:?}");
        // Centered on the line box [-base_line, line_height - base_line].
        let center2 = 2 * i32::from(info.ofs_y) + i32::from(info.box_h);
        let line_center2 = i32::from(font.line_height) - 2 * i32::from(font.base_line);
        assert!(
            (center2 - line_center2).abs() <= 1,
            "{c:?}: {center2} vs {line_center2}"
        );
    }
}

#[test]
fn chars_file_adds_characters() {
    let dir = std::env::temp_dir().join(format!("twine-cli-chars-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let list = dir.join("chars.txt");
    std::fs::write(&list, "é ñ\nü\n").unwrap();
    let mut o = opts(14, false);
    o.ranges = vec!["0x41".into()];
    o.chars_files = vec![list.clone()];
    let g = generate(&o, &root()).unwrap();
    assert_eq!(g.code_points[1..], ['A', 'é', 'ñ', 'ü']);
    assert!(g.source.contains("--chars-file"));
    let _ = std::fs::remove_dir_all(&dir);
}
