//! Rust source output of the font generator.

use std::fmt::Write as _;

use twine_text::encode::{FontData, KernData};
use twine_text::{BitmapFormat, CmapKind, Subpx};

use super::FontOptions;

fn bytes_array(out: &mut String, name: &str, data: &[u8]) {
    let _ = writeln!(out, "#[rustfmt::skip]\nstatic {name}: [u8; {}] = [", data.len());
    for chunk in data.chunks(16) {
        out.push_str("   ");
        for b in chunk {
            let _ = write!(out, " 0x{b:02x},");
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

fn u16_array(out: &mut String, name: &str, data: &[u16]) {
    let _ = writeln!(out, "#[rustfmt::skip]\nstatic {name}: [u16; {}] = [", data.len());
    for chunk in data.chunks(12) {
        out.push_str("   ");
        for v in chunk {
            let _ = write!(out, " 0x{v:04x},");
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

fn describe_char(c: char) -> String {
    if c == '\0' {
        "reserved".to_string()
    } else if c.is_control() || (0xE000..=0xF8FF).contains(&u32::from(c)) {
        format!("U+{:04X}", u32::from(c))
    } else {
        format!("U+{:04X} {c:?}", u32::from(c))
    }
}

/// Renders the Rust source of a generated font; returns it with the number of static data
/// bytes it contains.
#[must_use]
pub fn render_rust(
    opts: &FontOptions,
    d: &FontData,
    code_points: &[char],
    source: &(String, String),
    symbols: Option<&[(String, String)]>,
) -> (String, usize) {
    let n = &opts.name;
    let mut out = String::new();
    let mut flash = 0usize;
    let _ = writeln!(
        out,
        "// Generated by twine-cli {}: {}",
        env!("CARGO_PKG_VERSION"),
        opts.command_line()
    );
    let _ = writeln!(out, "// Source: {} SHA-256 {}", source.0, source.1);
    for (f, h) in symbols.unwrap_or_default() {
        let _ = writeln!(out, "// Symbols: {f} SHA-256 {h}");
    }
    let kern_pairs = match &d.kern {
        KernData::None => 0,
        KernData::Pairs { ids, .. } => ids.len(),
    };
    let fmt = match d.format {
        BitmapFormat::Plain => "plain",
        BitmapFormat::Compressed => "compressed",
        BitmapFormat::CompressedNoPrefilter => "compressed without prefilter",
    };
    let _ = writeln!(
        out,
        "// {} glyphs, line height {} px, base line {} px, {} bpp, {fmt} bitmaps, {kern_pairs} kerning pairs.",
        code_points.len() - 1,
        d.line_height,
        d.base_line,
        d.bpp
    );
    out.push_str("// Do not edit: regenerate with the command above.\n\n");

    bytes_array(&mut out, &format!("{n}_BITMAP"), &d.bitmap);
    flash += d.bitmap.len();

    let _ = writeln!(
        out,
        "#[rustfmt::skip]\nstatic {n}_GLYPHS: [twine_text::GlyphDsc; {}] = [",
        d.glyphs.len()
    );
    for (g, c) in d.glyphs.iter().zip(code_points) {
        let _ = writeln!(
            out,
            "    twine_text::GlyphDsc {{ bitmap_index: {}, adv_w: {}, box_w: {}, box_h: {}, ofs_x: {}, ofs_y: {} }}, // {}",
            g.bitmap_index,
            g.adv_w,
            g.box_w,
            g.box_h,
            g.ofs_x,
            g.ofs_y,
            describe_char(*c)
        );
    }
    out.push_str("];\n\n");
    flash += d.glyphs.len() * core::mem::size_of::<twine_text::GlyphDsc>();

    for (i, c) in d.cmaps.iter().enumerate() {
        if !c.unicode_list.is_empty() {
            u16_array(&mut out, &format!("{n}_UNICODE_LIST_{i}"), &c.unicode_list);
            flash += c.unicode_list.len() * 2;
        }
        if !c.ofs_u8.is_empty() {
            bytes_array(&mut out, &format!("{n}_GLYPH_ID_OFS_{i}"), &c.ofs_u8);
            flash += c.ofs_u8.len();
        }
        if !c.ofs_u16.is_empty() {
            u16_array(&mut out, &format!("{n}_GLYPH_ID_OFS_{i}"), &c.ofs_u16);
            flash += c.ofs_u16.len() * 2;
        }
    }
    let _ = writeln!(
        out,
        "#[rustfmt::skip]\nstatic {n}_CMAPS: [twine_text::Cmap; {}] = [",
        d.cmaps.len()
    );
    for (i, c) in d.cmaps.iter().enumerate() {
        let list = if c.unicode_list.is_empty() {
            "&[]".to_string()
        } else {
            format!("&{n}_UNICODE_LIST_{i}")
        };
        let ofs = match c.kind {
            CmapKind::Format0Full => format!("twine_text::GlyphIdOfs::U8(&{n}_GLYPH_ID_OFS_{i})"),
            CmapKind::SparseFull => format!("twine_text::GlyphIdOfs::U16(&{n}_GLYPH_ID_OFS_{i})"),
            _ => "twine_text::GlyphIdOfs::None".to_string(),
        };
        let _ = writeln!(
            out,
            "    twine_text::Cmap {{ range_start: 0x{:x}, range_length: {}, glyph_id_start: {}, unicode_list: {list}, glyph_id_ofs_list: {ofs}, kind: twine_text::CmapKind::{:?} }},",
            c.range_start, c.range_length, c.glyph_id_start, c.kind
        );
    }
    out.push_str("];\n\n");
    flash += d.cmaps.len() * core::mem::size_of::<twine_text::Cmap>();

    let kern = match &d.kern {
        KernData::None => "twine_text::Kern::None".to_string(),
        KernData::Pairs { ids, values } => {
            let u8_ids = d.kern.fits_u8();
            let (ty, w) = if u8_ids { ("u8", 1) } else { ("u16", 2) };
            let _ = writeln!(
                out,
                "#[rustfmt::skip]\nstatic {n}_KERN_PAIRS: [[{ty}; 2]; {}] = [",
                ids.len()
            );
            for chunk in ids.chunks(8) {
                out.push_str("   ");
                for p in chunk {
                    let _ = write!(out, " [{}, {}],", p[0], p[1]);
                }
                out.push('\n');
            }
            out.push_str("];\n\n");
            let _ = writeln!(
                out,
                "#[rustfmt::skip]\nstatic {n}_KERN_VALUES: [i8; {}] = [",
                values.len()
            );
            for chunk in values.chunks(16) {
                out.push_str("   ");
                for v in chunk {
                    let _ = write!(out, " {v},");
                }
                out.push('\n');
            }
            out.push_str("];\n\n");
            flash += ids.len() * 2 * w + values.len();
            format!(
                "twine_text::Kern::Pairs {{\n        glyph_ids: twine_text::KernPairIds::{}(&{n}_KERN_PAIRS),\n        values: &{n}_KERN_VALUES,\n    }}",
                if u8_ids { "U8" } else { "U16" }
            )
        }
    };

    let format = match d.format {
        BitmapFormat::Plain => "Plain",
        BitmapFormat::Compressed => "Compressed",
        BitmapFormat::CompressedNoPrefilter => "CompressedNoPrefilter",
    };
    let _ = writeln!(
        out,
        "static {n}_DATA: twine_text::BitmapFont = twine_text::BitmapFont {{\n    bpp: {},\n    bitmap: &{n}_BITMAP,\n    glyphs: &{n}_GLYPHS,\n    cmaps: &{n}_CMAPS,\n    kern: {kern},\n    kern_scale: {},\n    format: twine_text::BitmapFormat::{format},\n}};\n",
        d.bpp, d.kern_scale
    );
    flash += core::mem::size_of::<twine_text::BitmapFont>() + core::mem::size_of::<twine_text::Font>();

    let subpx = match d.subpx {
        Subpx::None => "None",
        Subpx::Hor => "Hor",
        Subpx::Ver => "Ver",
    };
    let _ = writeln!(
        out,
        "/// {} at {} px, {} bpp, {} glyphs (line height {} px).\npub static {n}: twine_text::Font = twine_text::Font {{\n    line_height: {},\n    base_line: {},\n    underline_position: {},\n    underline_thickness: {},\n    provider: &{n}_DATA,\n    fallback: None,\n    subpx: twine_text::Subpx::{subpx},\n}};",
        source.0,
        opts.size,
        d.bpp,
        code_points.len() - 1,
        d.line_height,
        d.line_height,
        d.base_line,
        d.underline_position,
        d.underline_thickness
    );
    (out, flash)
}
